/* PC-state VM that XOR-accumulates bytes below 0x80 (identity 0):
 *
 *   n = (x & 7) + 1;
 *   s = x; acc = 0x0;
 *   while (n) {
 *     uint64_t b = s & 0xFF;
 *     acc = acc ^ ((b < 0x80ull) ? b : 0ull);
 *     s >>= 8;
 *     n--;
 *   }
 *   return acc;
 *
 * Lift target: vm_byte_xor_ult_thresh64_loop_target.
 *
 * Generated by scripts/rewrite/generate_vm_sample.py for the predicate-gated
 * reducer family (byte stride, xor, ult).
 */
#include <stdio.h>
#include <stdint.h>

enum BXORVmPc {
    BXOR_INIT_ALL = 0,
    BXOR_CHECK    = 1,
    BXOR_BODY     = 2,
    BXOR_HALT     = 3,
};

__declspec(noinline)
uint64_t vm_byte_xor_ult_thresh64_loop_target(uint64_t x) {
    uint64_t n   = 0;
    uint64_t s   = 0;
    uint64_t acc = 0;
    int      pc  = BXOR_INIT_ALL;

    while (1) {
        if (pc == BXOR_INIT_ALL) {
            n = (x & 7ull) + 1ull;
            s = x;
            acc = 0;
            pc = BXOR_CHECK;
        } else if (pc == BXOR_CHECK) {
            pc = (n > 0ull) ? BXOR_BODY : BXOR_HALT;
        } else if (pc == BXOR_BODY) {
            uint64_t b = s & 0xFFull;
            acc = acc ^ ((b < 0x80ull) ? b : 0ull);
            s = s >> 8;
            n = n - 1ull;
            pc = BXOR_CHECK;
        } else if (pc == BXOR_HALT) {
            return acc;
        } else {
            return 0xFFFFFFFFFFFFFFFFull;
        }
    }
}

int main(void) {
    printf("vm_byte_xor_ult_thresh64_loop(0xCAFEBABE)=%llu\n",
           (unsigned long long)vm_byte_xor_ult_thresh64_loop_target(0xCAFEBABEull));
    return 0;
}
