/* PC-state VM that XOR-accumulates words below 0x8000 (identity 0):
 *
 *   n = (x & 3) + 1;
 *   s = x; acc = 0x0;
 *   while (n) {
 *     uint64_t w = s & 0xFFFF;
 *     acc = acc ^ ((w < 0x8000ull) ? w : 0ull);
 *     s >>= 16;
 *     n--;
 *   }
 *   return acc;
 *
 * Lift target: vm_word_xor_ult_thresh64_loop_target.
 *
 * Generated by scripts/rewrite/generate_vm_sample.py for the predicate-gated
 * reducer family (word stride, xor, ult).
 */
#include <stdio.h>
#include <stdint.h>

enum WXORVmPc {
    WXOR_INIT_ALL = 0,
    WXOR_CHECK    = 1,
    WXOR_BODY     = 2,
    WXOR_HALT     = 3,
};

__declspec(noinline)
uint64_t vm_word_xor_ult_thresh64_loop_target(uint64_t x) {
    uint64_t n   = 0;
    uint64_t s   = 0;
    uint64_t acc = 0;
    int      pc  = WXOR_INIT_ALL;

    while (1) {
        if (pc == WXOR_INIT_ALL) {
            n = (x & 3ull) + 1ull;
            s = x;
            acc = 0;
            pc = WXOR_CHECK;
        } else if (pc == WXOR_CHECK) {
            pc = (n > 0ull) ? WXOR_BODY : WXOR_HALT;
        } else if (pc == WXOR_BODY) {
            uint64_t w = s & 0xFFFFull;
            acc = acc ^ ((w < 0x8000ull) ? w : 0ull);
            s = s >> 16;
            n = n - 1ull;
            pc = WXOR_CHECK;
        } else if (pc == WXOR_HALT) {
            return acc;
        } else {
            return 0xFFFFFFFFFFFFFFFFull;
        }
    }
}

int main(void) {
    printf("vm_word_xor_ult_thresh64_loop(0xCAFEBABE)=%llu\n",
           (unsigned long long)vm_word_xor_ult_thresh64_loop_target(0xCAFEBABEull));
    return 0;
}
