#ifndef COMMON_MNEMONICS_H
#define COMMON_MNEMONICS_H

#include <cstdint>
enum class MnemonicInternal : uint16_t {
  Invalid = 0,
  AAA,
  AAD,
  AADD,
  AAM,
  AAND,
  AAS,
  ADC,
  ADCX,
  ADD,
  ADDPD,
  ADDPS,
  ADDSD,
  ADDSS,
  ADDSUBPD,
  ADDSUBPS,
  ADOX,
  AESDEC,
  AESDEC128KL,
  AESDEC256KL,
  AESDECLAST,
  AESDECWIDE128KL,
  AESDECWIDE256KL,
  AESENC,
  AESENC128KL,
  AESENC256KL,
  AESENCLAST,
  AESENCWIDE128KL,
  AESENCWIDE256KL,
  AESIMC,
  AESKEYGENASSIST,
  AND,
  ANDN,
  ANDNPD,
  ANDNPS,
  ANDPD,
  ANDPS,
  AOR,
  ARPL,
  AXOR,
  BEXTR,
  BLCFILL,
  BLCI,
  BLCIC,
  BLCMSK,
  BLCS,
  BLENDPD,
  BLENDPS,
  BLENDVPD,
  BLENDVPS,
  BLSFILL,
  BLSI,
  BLSIC,
  BLSMSK,
  BLSR,
  BNDCL,
  BNDCN,
  BNDCU,
  BNDLDX,
  BNDMK,
  BNDMOV,
  BNDSTX,
  BOUND,
  BSF,
  BSR,
  BSWAP,
  BT,
  BTC,
  BTR,
  BTS,
  BZHI,
  CALL,
  // CALL2,
  CBW,
  CDQ,
  CDQE,
  CLAC,
  CLC,
  CLD,
  CLDEMOTE,
  CLEVICT0,
  CLEVICT1,
  CLFLUSH,
  CLFLUSHOPT,
  CLGI,
  CLI,
  CLRSSBSY,
  CLTS,
  CLUI,
  CLWB,
  CLZERO,
  CMC,
  CMOVB,
  CMOVBE,
  CMOVL,
  CMOVLE,
  CMOVNB,
  CMOVNBE,
  CMOVNL,
  CMOVNLE,
  CMOVNO,
  CMOVNP,
  CMOVNS,
  CMOVNZ,
  CMOVO,
  CMOVP,
  CMOVS,
  CMOVZ,
  CMP,
  CMPPD,
  CMPPS,
  CMPSB,
  CMPSD,
  CMPSQ,
  CMPSS,
  CMPSW,
  CMPXCHG,
  CMPXCHG16B,
  CMPXCHG8B,
  COMISD,
  COMISS,
  CPUID,
  CQO,
  CRC32,
  CVTDQ2PD,
  CVTDQ2PS,
  CVTPD2DQ,
  CVTPD2PI,
  CVTPD2PS,
  CVTPI2PD,
  CVTPI2PS,
  CVTPS2DQ,
  CVTPS2PD,
  CVTPS2PI,
  CVTSD2SI,
  CVTSD2SS,
  CVTSI2SD,
  CVTSI2SS,
  CVTSS2SD,
  CVTSS2SI,
  CVTTPD2DQ,
  CVTTPD2PI,
  CVTTPS2DQ,
  CVTTPS2PI,
  CVTTSD2SI,
  CVTTSS2SI,
  CWD,
  CWDE,
  DAA,
  DAS,
  DEC,
  DELAY,
  DIV,
  DIVPD,
  DIVPS,
  DIVSD,
  DIVSS,
  DPPD,
  DPPS,
  EMMS,
  ENCLS,
  ENCLU,
  ENCLV,
  ENCODEKEY128,
  ENCODEKEY256,
  ENDBR32,
  ENDBR64,
  ENQCMD,
  ENQCMDS,
  ENTER,
  EXTRACTPS,
  EXTRQ,
  F2XM1,
  FABS,
  FADD,
  FADDP,
  FBLD,
  FBSTP,
  FCHS,
  FCMOVB,
  FCMOVBE,
  FCMOVE,
  FCMOVNB,
  FCMOVNBE,
  FCMOVNE,
  FCMOVNU,
  FCMOVU,
  FCOM,
  FCOMI,
  FCOMIP,
  FCOMP,
  FCOMPP,
  FCOS,
  FDECSTP,
  FDISI8087_NOP,
  FDIV,
  FDIVP,
  FDIVR,
  FDIVRP,
  FEMMS,
  FENI8087_NOP,
  FFREE,
  FFREEP,
  FIADD,
  FICOM,
  FICOMP,
  FIDIV,
  FIDIVR,
  FILD,
  FIMUL,
  FINCSTP,
  FIST,
  FISTP,
  FISTTP,
  FISUB,
  FISUBR,
  FLD,
  FLD1,
  FLDCW,
  FLDENV,
  FLDL2E,
  FLDL2T,
  FLDLG2,
  FLDLN2,
  FLDPI,
  FLDZ,
  FMUL,
  FMULP,
  FNCLEX,
  FNINIT,
  FNOP,
  FNSAVE,
  FNSTCW,
  FNSTENV,
  FNSTSW,
  FPATAN,
  FPREM,
  FPREM1,
  FPTAN,
  FRNDINT,
  FRSTOR,
  FSCALE,
  FSETPM287_NOP,
  FSIN,
  FSINCOS,
  FSQRT,
  FST,
  FSTP,
  FSTPNCE,
  FSUB,
  FSUBP,
  FSUBR,
  FSUBRP,
  FTST,
  FUCOM,
  FUCOMI,
  FUCOMIP,
  FUCOMP,
  FUCOMPP,
  FWAIT,
  FXAM,
  FXCH,
  FXRSTOR,
  FXRSTOR64,
  FXSAVE,
  FXSAVE64,
  FXTRACT,
  FYL2X,
  FYL2XP1,
  GETSEC,
  GF2P8AFFINEINVQB,
  GF2P8AFFINEQB,
  GF2P8MULB,
  HADDPD,
  HADDPS,
  HLT,
  HRESET,
  HSUBPD,
  HSUBPS,
  IDIV,
  IMUL,
  IN,
  INC,
  INCSSPD,
  INCSSPQ,
  INSB,
  INSD,
  INSERTPS,
  INSERTQ,
  INSW,
  INT,
  INT1,
  INT3,
  INTO,
  INVD,
  INVEPT,
  INVLPG,
  INVLPGA,
  INVLPGB,
  INVPCID,
  INVVPID,
  IRET,
  IRETD,
  IRETQ,
  JB,
  JBE,
  JCXZ,
  JECXZ,
  JKNZD,
  JKZD,
  JL,
  JLE,
  JMP,
  JNB,
  JNBE,
  JNL,
  JNLE,
  JNO,
  JNP,
  JNS,
  JNZ,
  JO,
  JP,
  JRCXZ,
  JS,
  JZ,
  KADDB,
  KADDD,
  KADDQ,
  KADDW,
  KAND,
  KANDB,
  KANDD,
  KANDN,
  KANDNB,
  KANDND,
  KANDNQ,
  KANDNR,
  KANDNW,
  KANDQ,
  KANDW,
  KCONCATH,
  KCONCATL,
  KEXTRACT,
  KMERGE2L1H,
  KMERGE2L1L,
  KMOV,
  KMOVB,
  KMOVD,
  KMOVQ,
  KMOVW,
  KNOT,
  KNOTB,
  KNOTD,
  KNOTQ,
  KNOTW,
  KOR,
  KORB,
  KORD,
  KORQ,
  KORTEST,
  KORTESTB,
  KORTESTD,
  KORTESTQ,
  KORTESTW,
  KORW,
  KSHIFTLB,
  KSHIFTLD,
  KSHIFTLQ,
  KSHIFTLW,
  KSHIFTRB,
  KSHIFTRD,
  KSHIFTRQ,
  KSHIFTRW,
  KTESTB,
  KTESTD,
  KTESTQ,
  KTESTW,
  KUNPCKBW,
  KUNPCKDQ,
  KUNPCKWD,
  KXNOR,
  KXNORB,
  KXNORD,
  KXNORQ,
  KXNORW,
  KXOR,
  KXORB,
  KXORD,
  KXORQ,
  KXORW,
  LAHF,
  LAR,
  LDDQU,
  LDMXCSR,
  LDS,
  LDTILECFG,
  LEA,
  LEAVE,
  LES,
  LFENCE,
  LFS,
  LGDT,
  LGS,
  LIDT,
  LLDT,
  LLWPCB,
  LMSW,
  LOADIWKEY,
  LODSB,
  LODSD,
  LODSQ,
  LODSW,
  LOOP,
  LOOPE,
  LOOPNE,
  LSL,
  LSS,
  LTR,
  LWPINS,
  LWPVAL,
  LZCNT,
  MASKMOVDQU,
  MASKMOVQ,
  MAXPD,
  MAXPS,
  MAXSD,
  MAXSS,
  MCOMMIT,
  MFENCE,
  MINPD,
  MINPS,
  MINSD,
  MINSS,
  MONITOR,
  MONITORX,
  MONTMUL,
  MOV,
  MOVAPD,
  MOVAPS,
  MOVBE,
  MOVD,
  MOVDDUP,
  MOVDIR64B,
  MOVDIRI,
  MOVDQ2Q,
  MOVDQA,
  MOVDQU,
  MOVHLPS,
  MOVHPD,
  MOVHPS,
  MOVLHPS,
  MOVLPD,
  MOVLPS,
  MOVMSKPD,
  MOVMSKPS,
  MOVNTDQ,
  MOVNTDQA,
  MOVNTI,
  MOVNTPD,
  MOVNTPS,
  MOVNTQ,
  MOVNTSD,
  MOVNTSS,
  MOVQ,
  MOVQ2DQ,
  MOVSB,
  MOVSD,
  MOVSHDUP,
  MOVSLDUP,
  MOVSQ,
  MOVSS,
  MOVSW,
  MOVSX,
  MOVSXD,
  MOVUPD,
  MOVUPS,
  MOVZX,
  MPSADBW,
  MUL,
  MULPD,
  MULPS,
  MULSD,
  MULSS,
  MULX,
  MWAIT,
  MWAITX,
  NEG,
  NOP,
  NOT,
  OR,
  ORPD,
  ORPS,
  OUT,
  OUTSB,
  OUTSD,
  OUTSW,
  PABSB,
  PABSD,
  PABSW,
  PACKSSDW,
  PACKSSWB,
  PACKUSDW,
  PACKUSWB,
  PADDB,
  PADDD,
  PADDQ,
  PADDSB,
  PADDSW,
  PADDUSB,
  PADDUSW,
  PADDW,
  PALIGNR,
  PAND,
  PANDN,
  PAUSE,
  PAVGB,
  PAVGUSB,
  PAVGW,
  PBLENDVB,
  PBLENDW,
  PBNDKB,
  PCLMULQDQ,
  PCMPEQB,
  PCMPEQD,
  PCMPEQQ,
  PCMPEQW,
  PCMPESTRI,
  PCMPESTRM,
  PCMPGTB,
  PCMPGTD,
  PCMPGTQ,
  PCMPGTW,
  PCMPISTRI,
  PCMPISTRM,
  PCOMMIT,
  PCONFIG,
  PDEP,
  PEXT,
  PEXTRB,
  PEXTRD,
  PEXTRQ,
  PEXTRW,
  PF2ID,
  PF2IW,
  PFACC,
  PFADD,
  PFCMPEQ,
  PFCMPGE,
  PFCMPGT,
  PFCPIT1,
  PFMAX,
  PFMIN,
  PFMUL,
  PFNACC,
  PFPNACC,
  PFRCP,
  PFRCPIT2,
  PFRSQIT1,
  PFSQRT,
  PFSUB,
  PFSUBR,
  PHADDD,
  PHADDSW,
  PHADDW,
  PHMINPOSUW,
  PHSUBD,
  PHSUBSW,
  PHSUBW,
  PI2FD,
  PI2FW,
  PINSRB,
  PINSRD,
  PINSRQ,
  PINSRW,
  PMADDUBSW,
  PMADDWD,
  PMAXSB,
  PMAXSD,
  PMAXSW,
  PMAXUB,
  PMAXUD,
  PMAXUW,
  PMINSB,
  PMINSD,
  PMINSW,
  PMINUB,
  PMINUD,
  PMINUW,
  PMOVMSKB,
  PMOVSXBD,
  PMOVSXBQ,
  PMOVSXBW,
  PMOVSXDQ,
  PMOVSXWD,
  PMOVSXWQ,
  PMOVZXBD,
  PMOVZXBQ,
  PMOVZXBW,
  PMOVZXDQ,
  PMOVZXWD,
  PMOVZXWQ,
  PMULDQ,
  PMULHRSW,
  PMULHRW,
  PMULHUW,
  PMULHW,
  PMULLD,
  PMULLW,
  PMULUDQ,
  POP,
  POPA,
  POPAD,
  POPCNT,
  POPF,
  POPFD,
  POPFQ,
  POR,
  PREFETCH,
  PREFETCHIT0,
  PREFETCHIT1,
  PREFETCHNTA,
  PREFETCHT0,
  PREFETCHT1,
  PREFETCHT2,
  PREFETCHW,
  PREFETCHWT1,
  PSADBW,
  PSHUFB,
  PSHUFD,
  PSHUFHW,
  PSHUFLW,
  PSHUFW,
  PSIGNB,
  PSIGND,
  PSIGNW,
  PSLLD,
  PSLLDQ,
  PSLLQ,
  PSLLW,
  PSMASH,
  PSRAD,
  PSRAW,
  PSRLD,
  PSRLDQ,
  PSRLQ,
  PSRLW,
  PSUBB,
  PSUBD,
  PSUBQ,
  PSUBSB,
  PSUBSW,
  PSUBUSB,
  PSUBUSW,
  PSUBW,
  PSWAPD,
  PTEST,
  PTWRITE,
  PUNPCKHBW,
  PUNPCKHDQ,
  PUNPCKHQDQ,
  PUNPCKHWD,
  PUNPCKLBW,
  PUNPCKLDQ,
  PUNPCKLQDQ,
  PUNPCKLWD,
  PUSH,
  PUSHA,
  PUSHAD,
  PUSHF,
  PUSHFD,
  PUSHFQ,
  PVALIDATE,
  PXOR,
  RCL,
  RCPPS,
  RCPSS,
  RCR,
  RDFSBASE,
  RDGSBASE,
  RDMSR,
  RDMSRLIST,
  RDPID,
  RDPKRU,
  RDPMC,
  RDPRU,
  RDRAND,
  RDSEED,
  RDSSPD,
  RDSSPQ,
  RDTSC,
  RDTSCP,
  RET,
  RMPADJUST,
  RMPUPDATE,
  ROL,
  ROR,
  RORX,
  ROUNDPD,
  ROUNDPS,
  ROUNDSD,
  ROUNDSS,
  RSM,
  RSQRTPS,
  RSQRTSS,
  RSTORSSP,
  SAHF,
  SALC,
  SAR,
  SARX,
  SAVEPREVSSP,
  SBB,
  SCASB,
  SCASD,
  SCASQ,
  SCASW,
  SEAMCALL,
  SEAMOPS,
  SEAMRET,
  SENDUIPI,
  SERIALIZE,
  SETB,
  SETBE,
  SETL,
  SETLE,
  SETNB,
  SETNBE,
  SETNL,
  SETNLE,
  SETNO,
  SETNP,
  SETNS,
  SETNZ,
  SETO,
  SETP,
  SETS,
  SETSSBSY,
  SETZ,
  SFENCE,
  SGDT,
  SHA1MSG1,
  SHA1MSG2,
  SHA1NEXTE,
  SHA1RNDS4,
  SHA256MSG1,
  SHA256MSG2,
  SHA256RNDS2,
  SHL,
  SHLD,
  SHLX,
  SHR,
  SHRD,
  SHRX,
  SHUFPD,
  SHUFPS,
  SIDT,
  SKINIT,
  SLDT,
  SLWPCB,
  SMSW,
  SPFLT,
  SQRTPD,
  SQRTPS,
  SQRTSD,
  SQRTSS,
  STAC,
  STC,
  STD,
  STGI,
  STI,
  STMXCSR,
  STOSB,
  STOSD,
  STOSQ,
  STOSW,
  STR,
  STTILECFG,
  STUI,
  SUB,
  SUBPD,
  SUBPS,
  SUBSD,
  SUBSS,
  SWAPGS,
  SYSCALL,
  SYSENTER,
  SYSEXIT,
  SYSRET,
  T1MSKC,
  TDCALL,
  TDPBF16PS,
  TDPBSSD,
  TDPBSUD,
  TDPBUSD,
  TDPBUUD,
  TDPFP16PS,
  TEST,
  TESTUI,
  TILELOADD,
  TILELOADDT1,
  TILERELEASE,
  TILESTORED,
  TILEZERO,
  TLBSYNC,
  TPAUSE,
  TZCNT,
  TZCNTI,
  TZMSK,
  UCOMISD,
  UCOMISS,
  UD0,
  UD1,
  UD2,
  UIRET,
  UMONITOR,
  UMWAIT,
  UNPCKHPD,
  UNPCKHPS,
  UNPCKLPD,
  UNPCKLPS,
  V4FMADDPS,
  V4FMADDSS,
  V4FNMADDPS,
  V4FNMADDSS,
  VADDNPD,
  VADDNPS,
  VADDPD,
  VADDPH,
  VADDPS,
  VADDSD,
  VADDSETSPS,
  VADDSH,
  VADDSS,
  VADDSUBPD,
  VADDSUBPS,
  VAESDEC,
  VAESDECLAST,
  VAESENC,
  VAESENCLAST,
  VAESIMC,
  VAESKEYGENASSIST,
  VALIGND,
  VALIGNQ,
  VANDNPD,
  VANDNPS,
  VANDPD,
  VANDPS,
  VBCSTNEBF162PS,
  VBCSTNESH2PS,
  VBLENDMPD,
  VBLENDMPS,
  VBLENDPD,
  VBLENDPS,
  VBLENDVPD,
  VBLENDVPS,
  VBROADCASTF128,
  VBROADCASTF32X2,
  VBROADCASTF32X4,
  VBROADCASTF32X8,
  VBROADCASTF64X2,
  VBROADCASTF64X4,
  VBROADCASTI128,
  VBROADCASTI32X2,
  VBROADCASTI32X4,
  VBROADCASTI32X8,
  VBROADCASTI64X2,
  VBROADCASTI64X4,
  VBROADCASTSD,
  VBROADCASTSS,
  VCMPPD,
  VCMPPH,
  VCMPPS,
  VCMPSD,
  VCMPSH,
  VCMPSS,
  VCOMISD,
  VCOMISH,
  VCOMISS,
  VCOMPRESSPD,
  VCOMPRESSPS,
  VCVTDQ2PD,
  VCVTDQ2PH,
  VCVTDQ2PS,
  VCVTFXPNTDQ2PS,
  VCVTFXPNTPD2DQ,
  VCVTFXPNTPD2UDQ,
  VCVTFXPNTPS2DQ,
  VCVTFXPNTPS2UDQ,
  VCVTFXPNTUDQ2PS,
  VCVTNE2PS2BF16,
  VCVTNEEBF162PS,
  VCVTNEEPH2PS,
  VCVTNEOBF162PS,
  VCVTNEOPH2PS,
  VCVTNEPS2BF16,
  VCVTPD2DQ,
  VCVTPD2PH,
  VCVTPD2PS,
  VCVTPD2QQ,
  VCVTPD2UDQ,
  VCVTPD2UQQ,
  VCVTPH2DQ,
  VCVTPH2PD,
  VCVTPH2PS,
  VCVTPH2PSX,
  VCVTPH2QQ,
  VCVTPH2UDQ,
  VCVTPH2UQQ,
  VCVTPH2UW,
  VCVTPH2W,
  VCVTPS2DQ,
  VCVTPS2PD,
  VCVTPS2PH,
  VCVTPS2PHX,
  VCVTPS2QQ,
  VCVTPS2UDQ,
  VCVTPS2UQQ,
  VCVTQQ2PD,
  VCVTQQ2PH,
  VCVTQQ2PS,
  VCVTSD2SH,
  VCVTSD2SI,
  VCVTSD2SS,
  VCVTSD2USI,
  VCVTSH2SD,
  VCVTSH2SI,
  VCVTSH2SS,
  VCVTSH2USI,
  VCVTSI2SD,
  VCVTSI2SH,
  VCVTSI2SS,
  VCVTSS2SD,
  VCVTSS2SH,
  VCVTSS2SI,
  VCVTSS2USI,
  VCVTTPD2DQ,
  VCVTTPD2QQ,
  VCVTTPD2UDQ,
  VCVTTPD2UQQ,
  VCVTTPH2DQ,
  VCVTTPH2QQ,
  VCVTTPH2UDQ,
  VCVTTPH2UQQ,
  VCVTTPH2UW,
  VCVTTPH2W,
  VCVTTPS2DQ,
  VCVTTPS2QQ,
  VCVTTPS2UDQ,
  VCVTTPS2UQQ,
  VCVTTSD2SI,
  VCVTTSD2USI,
  VCVTTSH2SI,
  VCVTTSH2USI,
  VCVTTSS2SI,
  VCVTTSS2USI,
  VCVTUDQ2PD,
  VCVTUDQ2PH,
  VCVTUDQ2PS,
  VCVTUQQ2PD,
  VCVTUQQ2PH,
  VCVTUQQ2PS,
  VCVTUSI2SD,
  VCVTUSI2SH,
  VCVTUSI2SS,
  VCVTUW2PH,
  VCVTW2PH,
  VDBPSADBW,
  VDIVPD,
  VDIVPH,
  VDIVPS,
  VDIVSD,
  VDIVSH,
  VDIVSS,
  VDPBF16PS,
  VDPPD,
  VDPPS,
  VERR,
  VERW,
  VEXP223PS,
  VEXP2PD,
  VEXP2PS,
  VEXPANDPD,
  VEXPANDPS,
  VEXTRACTF128,
  VEXTRACTF32X4,
  VEXTRACTF32X8,
  VEXTRACTF64X2,
  VEXTRACTF64X4,
  VEXTRACTI128,
  VEXTRACTI32X4,
  VEXTRACTI32X8,
  VEXTRACTI64X2,
  VEXTRACTI64X4,
  VEXTRACTPS,
  VFCMADDCPH,
  VFCMADDCSH,
  VFCMULCPH,
  VFCMULCSH,
  VFIXUPIMMPD,
  VFIXUPIMMPS,
  VFIXUPIMMSD,
  VFIXUPIMMSS,
  VFIXUPNANPD,
  VFIXUPNANPS,
  VFMADD132PD,
  VFMADD132PH,
  VFMADD132PS,
  VFMADD132SD,
  VFMADD132SH,
  VFMADD132SS,
  VFMADD213PD,
  VFMADD213PH,
  VFMADD213PS,
  VFMADD213SD,
  VFMADD213SH,
  VFMADD213SS,
  VFMADD231PD,
  VFMADD231PH,
  VFMADD231PS,
  VFMADD231SD,
  VFMADD231SH,
  VFMADD231SS,
  VFMADD233PS,
  VFMADDCPH,
  VFMADDCSH,
  VFMADDPD,
  VFMADDPS,
  VFMADDSD,
  VFMADDSS,
  VFMADDSUB132PD,
  VFMADDSUB132PH,
  VFMADDSUB132PS,
  VFMADDSUB213PD,
  VFMADDSUB213PH,
  VFMADDSUB213PS,
  VFMADDSUB231PD,
  VFMADDSUB231PH,
  VFMADDSUB231PS,
  VFMADDSUBPD,
  VFMADDSUBPS,
  VFMSUB132PD,
  VFMSUB132PH,
  VFMSUB132PS,
  VFMSUB132SD,
  VFMSUB132SH,
  VFMSUB132SS,
  VFMSUB213PD,
  VFMSUB213PH,
  VFMSUB213PS,
  VFMSUB213SD,
  VFMSUB213SH,
  VFMSUB213SS,
  VFMSUB231PD,
  VFMSUB231PH,
  VFMSUB231PS,
  VFMSUB231SD,
  VFMSUB231SH,
  VFMSUB231SS,
  VFMSUBADD132PD,
  VFMSUBADD132PH,
  VFMSUBADD132PS,
  VFMSUBADD213PD,
  VFMSUBADD213PH,
  VFMSUBADD213PS,
  VFMSUBADD231PD,
  VFMSUBADD231PH,
  VFMSUBADD231PS,
  VFMSUBADDPD,
  VFMSUBADDPS,
  VFMSUBPD,
  VFMSUBPS,
  VFMSUBSD,
  VFMSUBSS,
  VFMULCPH,
  VFMULCSH,
  VFNMADD132PD,
  VFNMADD132PH,
  VFNMADD132PS,
  VFNMADD132SD,
  VFNMADD132SH,
  VFNMADD132SS,
  VFNMADD213PD,
  VFNMADD213PH,
  VFNMADD213PS,
  VFNMADD213SD,
  VFNMADD213SH,
  VFNMADD213SS,
  VFNMADD231PD,
  VFNMADD231PH,
  VFNMADD231PS,
  VFNMADD231SD,
  VFNMADD231SH,
  VFNMADD231SS,
  VFNMADDPD,
  VFNMADDPS,
  VFNMADDSD,
  VFNMADDSS,
  VFNMSUB132PD,
  VFNMSUB132PH,
  VFNMSUB132PS,
  VFNMSUB132SD,
  VFNMSUB132SH,
  VFNMSUB132SS,
  VFNMSUB213PD,
  VFNMSUB213PH,
  VFNMSUB213PS,
  VFNMSUB213SD,
  VFNMSUB213SH,
  VFNMSUB213SS,
  VFNMSUB231PD,
  VFNMSUB231PH,
  VFNMSUB231PS,
  VFNMSUB231SD,
  VFNMSUB231SH,
  VFNMSUB231SS,
  VFNMSUBPD,
  VFNMSUBPS,
  VFNMSUBSD,
  VFNMSUBSS,
  VFPCLASSPD,
  VFPCLASSPH,
  VFPCLASSPS,
  VFPCLASSSD,
  VFPCLASSSH,
  VFPCLASSSS,
  VFRCZPD,
  VFRCZPS,
  VFRCZSD,
  VFRCZSS,
  VGATHERDPD,
  VGATHERDPS,
  VGATHERPF0DPD,
  VGATHERPF0DPS,
  VGATHERPF0HINTDPD,
  VGATHERPF0HINTDPS,
  VGATHERPF0QPD,
  VGATHERPF0QPS,
  VGATHERPF1DPD,
  VGATHERPF1DPS,
  VGATHERPF1QPD,
  VGATHERPF1QPS,
  VGATHERQPD,
  VGATHERQPS,
  VGETEXPPD,
  VGETEXPPH,
  VGETEXPPS,
  VGETEXPSD,
  VGETEXPSH,
  VGETEXPSS,
  VGETMANTPD,
  VGETMANTPH,
  VGETMANTPS,
  VGETMANTSD,
  VGETMANTSH,
  VGETMANTSS,
  VGF2P8AFFINEINVQB,
  VGF2P8AFFINEQB,
  VGF2P8MULB,
  VGMAXABSPS,
  VGMAXPD,
  VGMAXPS,
  VGMINPD,
  VGMINPS,
  VHADDPD,
  VHADDPS,
  VHSUBPD,
  VHSUBPS,
  VINSERTF128,
  VINSERTF32X4,
  VINSERTF32X8,
  VINSERTF64X2,
  VINSERTF64X4,
  VINSERTI128,
  VINSERTI32X4,
  VINSERTI32X8,
  VINSERTI64X2,
  VINSERTI64X4,
  VINSERTPS,
  VLDDQU,
  VLDMXCSR,
  VLOADUNPACKHD,
  VLOADUNPACKHPD,
  VLOADUNPACKHPS,
  VLOADUNPACKHQ,
  VLOADUNPACKLD,
  VLOADUNPACKLPD,
  VLOADUNPACKLPS,
  VLOADUNPACKLQ,
  VLOG2PS,
  VMASKMOVDQU,
  VMASKMOVPD,
  VMASKMOVPS,
  VMAXPD,
  VMAXPH,
  VMAXPS,
  VMAXSD,
  VMAXSH,
  VMAXSS,
  VMCALL,
  VMCLEAR,
  VMFUNC,
  VMINPD,
  VMINPH,
  VMINPS,
  VMINSD,
  VMINSH,
  VMINSS,
  VMLAUNCH,
  VMLOAD,
  VMMCALL,
  VMOVAPD,
  VMOVAPS,
  VMOVD,
  VMOVDDUP,
  VMOVDQA,
  VMOVDQA32,
  VMOVDQA64,
  VMOVDQU,
  VMOVDQU16,
  VMOVDQU32,
  VMOVDQU64,
  VMOVDQU8,
  VMOVHLPS,
  VMOVHPD,
  VMOVHPS,
  VMOVLHPS,
  VMOVLPD,
  VMOVLPS,
  VMOVMSKPD,
  VMOVMSKPS,
  VMOVNRAPD,
  VMOVNRAPS,
  VMOVNRNGOAPD,
  VMOVNRNGOAPS,
  VMOVNTDQ,
  VMOVNTDQA,
  VMOVNTPD,
  VMOVNTPS,
  VMOVQ,
  VMOVSD,
  VMOVSH,
  VMOVSHDUP,
  VMOVSLDUP,
  VMOVSS,
  VMOVUPD,
  VMOVUPS,
  VMOVW,
  VMPSADBW,
  VMPTRLD,
  VMPTRST,
  VMREAD,
  VMRESUME,
  VMRUN,
  VMSAVE,
  VMULPD,
  VMULPH,
  VMULPS,
  VMULSD,
  VMULSH,
  VMULSS,
  VMWRITE,
  VMXOFF,
  VMXON,
  VORPD,
  VORPS,
  VP2INTERSECTD,
  VP2INTERSECTQ,
  VP4DPWSSD,
  VP4DPWSSDS,
  VPABSB,
  VPABSD,
  VPABSQ,
  VPABSW,
  VPACKSSDW,
  VPACKSSWB,
  VPACKSTOREHD,
  VPACKSTOREHPD,
  VPACKSTOREHPS,
  VPACKSTOREHQ,
  VPACKSTORELD,
  VPACKSTORELPD,
  VPACKSTORELPS,
  VPACKSTORELQ,
  VPACKUSDW,
  VPACKUSWB,
  VPADCD,
  VPADDB,
  VPADDD,
  VPADDQ,
  VPADDSB,
  VPADDSETCD,
  VPADDSETSD,
  VPADDSW,
  VPADDUSB,
  VPADDUSW,
  VPADDW,
  VPALIGNR,
  VPAND,
  VPANDD,
  VPANDN,
  VPANDND,
  VPANDNQ,
  VPANDQ,
  VPAVGB,
  VPAVGW,
  VPBLENDD,
  VPBLENDMB,
  VPBLENDMD,
  VPBLENDMQ,
  VPBLENDMW,
  VPBLENDVB,
  VPBLENDW,
  VPBROADCASTB,
  VPBROADCASTD,
  VPBROADCASTMB2Q,
  VPBROADCASTMW2D,
  VPBROADCASTQ,
  VPBROADCASTW,
  VPCLMULQDQ,
  VPCMOV,
  VPCMPB,
  VPCMPD,
  VPCMPEQB,
  VPCMPEQD,
  VPCMPEQQ,
  VPCMPEQW,
  VPCMPESTRI,
  VPCMPESTRM,
  VPCMPGTB,
  VPCMPGTD,
  VPCMPGTQ,
  VPCMPGTW,
  VPCMPISTRI,
  VPCMPISTRM,
  VPCMPLTD,
  VPCMPQ,
  VPCMPUB,
  VPCMPUD,
  VPCMPUQ,
  VPCMPUW,
  VPCMPW,
  VPCOMB,
  VPCOMD,
  VPCOMPRESSB,
  VPCOMPRESSD,
  VPCOMPRESSQ,
  VPCOMPRESSW,
  VPCOMQ,
  VPCOMUB,
  VPCOMUD,
  VPCOMUQ,
  VPCOMUW,
  VPCOMW,
  VPCONFLICTD,
  VPCONFLICTQ,
  VPDPBSSD,
  VPDPBSSDS,
  VPDPBSUD,
  VPDPBSUDS,
  VPDPBUSD,
  VPDPBUSDS,
  VPDPBUUD,
  VPDPBUUDS,
  VPDPWSSD,
  VPDPWSSDS,
  VPDPWSUD,
  VPDPWSUDS,
  VPDPWUSD,
  VPDPWUSDS,
  VPDPWUUD,
  VPDPWUUDS,
  VPERM2F128,
  VPERM2I128,
  VPERMB,
  VPERMD,
  VPERMF32X4,
  VPERMI2B,
  VPERMI2D,
  VPERMI2PD,
  VPERMI2PS,
  VPERMI2Q,
  VPERMI2W,
  VPERMIL2PD,
  VPERMIL2PS,
  VPERMILPD,
  VPERMILPS,
  VPERMPD,
  VPERMPS,
  VPERMQ,
  VPERMT2B,
  VPERMT2D,
  VPERMT2PD,
  VPERMT2PS,
  VPERMT2Q,
  VPERMT2W,
  VPERMW,
  VPEXPANDB,
  VPEXPANDD,
  VPEXPANDQ,
  VPEXPANDW,
  VPEXTRB,
  VPEXTRD,
  VPEXTRQ,
  VPEXTRW,
  VPGATHERDD,
  VPGATHERDQ,
  VPGATHERQD,
  VPGATHERQQ,
  VPHADDBD,
  VPHADDBQ,
  VPHADDBW,
  VPHADDD,
  VPHADDDQ,
  VPHADDSW,
  VPHADDUBD,
  VPHADDUBQ,
  VPHADDUBW,
  VPHADDUDQ,
  VPHADDUWD,
  VPHADDUWQ,
  VPHADDW,
  VPHADDWD,
  VPHADDWQ,
  VPHMINPOSUW,
  VPHSUBBW,
  VPHSUBD,
  VPHSUBDQ,
  VPHSUBSW,
  VPHSUBW,
  VPHSUBWD,
  VPINSRB,
  VPINSRD,
  VPINSRQ,
  VPINSRW,
  VPLZCNTD,
  VPLZCNTQ,
  VPMACSDD,
  VPMACSDQH,
  VPMACSDQL,
  VPMACSSDD,
  VPMACSSDQH,
  VPMACSSDQL,
  VPMACSSWD,
  VPMACSSWW,
  VPMACSWD,
  VPMACSWW,
  VPMADCSSWD,
  VPMADCSWD,
  VPMADD231D,
  VPMADD233D,
  VPMADD52HUQ,
  VPMADD52LUQ,
  VPMADDUBSW,
  VPMADDWD,
  VPMASKMOVD,
  VPMASKMOVQ,
  VPMAXSB,
  VPMAXSD,
  VPMAXSQ,
  VPMAXSW,
  VPMAXUB,
  VPMAXUD,
  VPMAXUQ,
  VPMAXUW,
  VPMINSB,
  VPMINSD,
  VPMINSQ,
  VPMINSW,
  VPMINUB,
  VPMINUD,
  VPMINUQ,
  VPMINUW,
  VPMOVB2M,
  VPMOVD2M,
  VPMOVDB,
  VPMOVDW,
  VPMOVM2B,
  VPMOVM2D,
  VPMOVM2Q,
  VPMOVM2W,
  VPMOVMSKB,
  VPMOVQ2M,
  VPMOVQB,
  VPMOVQD,
  VPMOVQW,
  VPMOVSDB,
  VPMOVSDW,
  VPMOVSQB,
  VPMOVSQD,
  VPMOVSQW,
  VPMOVSWB,
  VPMOVSXBD,
  VPMOVSXBQ,
  VPMOVSXBW,
  VPMOVSXDQ,
  VPMOVSXWD,
  VPMOVSXWQ,
  VPMOVUSDB,
  VPMOVUSDW,
  VPMOVUSQB,
  VPMOVUSQD,
  VPMOVUSQW,
  VPMOVUSWB,
  VPMOVW2M,
  VPMOVWB,
  VPMOVZXBD,
  VPMOVZXBQ,
  VPMOVZXBW,
  VPMOVZXDQ,
  VPMOVZXWD,
  VPMOVZXWQ,
  VPMULDQ,
  VPMULHD,
  VPMULHRSW,
  VPMULHUD,
  VPMULHUW,
  VPMULHW,
  VPMULLD,
  VPMULLQ,
  VPMULLW,
  VPMULTISHIFTQB,
  VPMULUDQ,
  VPOPCNTB,
  VPOPCNTD,
  VPOPCNTQ,
  VPOPCNTW,
  VPOR,
  VPORD,
  VPORQ,
  VPPERM,
  VPREFETCH0,
  VPREFETCH1,
  VPREFETCH2,
  VPREFETCHE0,
  VPREFETCHE1,
  VPREFETCHE2,
  VPREFETCHENTA,
  VPREFETCHNTA,
  VPROLD,
  VPROLQ,
  VPROLVD,
  VPROLVQ,
  VPRORD,
  VPRORQ,
  VPRORVD,
  VPRORVQ,
  VPROTB,
  VPROTD,
  VPROTQ,
  VPROTW,
  VPSADBW,
  VPSBBD,
  VPSBBRD,
  VPSCATTERDD,
  VPSCATTERDQ,
  VPSCATTERQD,
  VPSCATTERQQ,
  VPSHAB,
  VPSHAD,
  VPSHAQ,
  VPSHAW,
  VPSHLB,
  VPSHLD,
  VPSHLDD,
  VPSHLDQ,
  VPSHLDVD,
  VPSHLDVQ,
  VPSHLDVW,
  VPSHLDW,
  VPSHLQ,
  VPSHLW,
  VPSHRDD,
  VPSHRDQ,
  VPSHRDVD,
  VPSHRDVQ,
  VPSHRDVW,
  VPSHRDW,
  VPSHUFB,
  VPSHUFBITQMB,
  VPSHUFD,
  VPSHUFHW,
  VPSHUFLW,
  VPSIGNB,
  VPSIGND,
  VPSIGNW,
  VPSLLD,
  VPSLLDQ,
  VPSLLQ,
  VPSLLVD,
  VPSLLVQ,
  VPSLLVW,
  VPSLLW,
  VPSRAD,
  VPSRAQ,
  VPSRAVD,
  VPSRAVQ,
  VPSRAVW,
  VPSRAW,
  VPSRLD,
  VPSRLDQ,
  VPSRLQ,
  VPSRLVD,
  VPSRLVQ,
  VPSRLVW,
  VPSRLW,
  VPSUBB,
  VPSUBD,
  VPSUBQ,
  VPSUBRD,
  VPSUBRSETBD,
  VPSUBSB,
  VPSUBSETBD,
  VPSUBSW,
  VPSUBUSB,
  VPSUBUSW,
  VPSUBW,
  VPTERNLOGD,
  VPTERNLOGQ,
  VPTEST,
  VPTESTMB,
  VPTESTMD,
  VPTESTMQ,
  VPTESTMW,
  VPTESTNMB,
  VPTESTNMD,
  VPTESTNMQ,
  VPTESTNMW,
  VPUNPCKHBW,
  VPUNPCKHDQ,
  VPUNPCKHQDQ,
  VPUNPCKHWD,
  VPUNPCKLBW,
  VPUNPCKLDQ,
  VPUNPCKLQDQ,
  VPUNPCKLWD,
  VPXOR,
  VPXORD,
  VPXORQ,
  VRANGEPD,
  VRANGEPS,
  VRANGESD,
  VRANGESS,
  VRCP14PD,
  VRCP14PS,
  VRCP14SD,
  VRCP14SS,
  VRCP23PS,
  VRCP28PD,
  VRCP28PS,
  VRCP28SD,
  VRCP28SS,
  VRCPPH,
  VRCPPS,
  VRCPSH,
  VRCPSS,
  VREDUCEPD,
  VREDUCEPH,
  VREDUCEPS,
  VREDUCESD,
  VREDUCESH,
  VREDUCESS,
  VRNDFXPNTPD,
  VRNDFXPNTPS,
  VRNDSCALEPD,
  VRNDSCALEPH,
  VRNDSCALEPS,
  VRNDSCALESD,
  VRNDSCALESH,
  VRNDSCALESS,
  VROUNDPD,
  VROUNDPS,
  VROUNDSD,
  VROUNDSS,
  VRSQRT14PD,
  VRSQRT14PS,
  VRSQRT14SD,
  VRSQRT14SS,
  VRSQRT23PS,
  VRSQRT28PD,
  VRSQRT28PS,
  VRSQRT28SD,
  VRSQRT28SS,
  VRSQRTPH,
  VRSQRTPS,
  VRSQRTSH,
  VRSQRTSS,
  VSCALEFPD,
  VSCALEFPH,
  VSCALEFPS,
  VSCALEFSD,
  VSCALEFSH,
  VSCALEFSS,
  VSCALEPS,
  VSCATTERDPD,
  VSCATTERDPS,
  VSCATTERPF0DPD,
  VSCATTERPF0DPS,
  VSCATTERPF0HINTDPD,
  VSCATTERPF0HINTDPS,
  VSCATTERPF0QPD,
  VSCATTERPF0QPS,
  VSCATTERPF1DPD,
  VSCATTERPF1DPS,
  VSCATTERPF1QPD,
  VSCATTERPF1QPS,
  VSCATTERQPD,
  VSCATTERQPS,
  VSHA512MSG1,
  VSHA512MSG2,
  VSHA512RNDS2,
  VSHUFF32X4,
  VSHUFF64X2,
  VSHUFI32X4,
  VSHUFI64X2,
  VSHUFPD,
  VSHUFPS,
  VSM3MSG1,
  VSM3MSG2,
  VSM3RNDS2,
  VSM4KEY4,
  VSM4RNDS4,
  VSQRTPD,
  VSQRTPH,
  VSQRTPS,
  VSQRTSD,
  VSQRTSH,
  VSQRTSS,
  VSTMXCSR,
  VSUBPD,
  VSUBPH,
  VSUBPS,
  VSUBRPD,
  VSUBRPS,
  VSUBSD,
  VSUBSH,
  VSUBSS,
  VTESTPD,
  VTESTPS,
  VUCOMISD,
  VUCOMISH,
  VUCOMISS,
  VUNPCKHPD,
  VUNPCKHPS,
  VUNPCKLPD,
  VUNPCKLPS,
  VXORPD,
  VXORPS,
  VZEROALL,
  VZEROUPPER,
  WBINVD,
  WRFSBASE,
  WRGSBASE,
  WRMSR,
  WRMSRLIST,
  WRMSRNS,
  WRPKRU,
  WRSSD,
  WRSSQ,
  WRUSSD,
  WRUSSQ,
  XABORT,
  XADD,
  XBEGIN,
  XCHG,
  XCRYPT_CBC,
  XCRYPT_CFB,
  XCRYPT_CTR,
  XCRYPT_ECB,
  XCRYPT_OFB,
  XEND,
  XGETBV,
  XLAT,
  XOR,
  XORPD,
  XORPS,
  XRESLDTRK,
  XRSTOR,
  XRSTOR64,
  XRSTORS,
  XRSTORS64,
  XSAVE,
  XSAVE64,
  XSAVEC,
  XSAVEC64,
  XSAVEOPT,
  XSAVEOPT64,
  XSAVES,
  XSAVES64,
  XSETBV,
  XSHA1,
  XSHA256,
  XSTORE,
  XSUSLDTRK,
  XTEST,
  MNEMONIC_END = XTEST,

};

template <typename T>
concept Mnemonics = requires() {
  { T::AAA };
  { T::AAD };
  { T::AADD };
  { T::AAM };
  { T::AAND };
  { T::AAS };
  { T::ADC };
  { T::ADCX };
  { T::ADD };
  { T::ADDPD };
  { T::ADDPS };
  { T::ADDSD };
  { T::ADDSS };
  { T::ADDSUBPD };
  { T::ADDSUBPS };
  { T::ADOX };
  { T::AESDEC };
  { T::AESDEC128KL };
  { T::AESDEC256KL };
  { T::AESDECLAST };
  { T::AESDECWIDE128KL };
  { T::AESDECWIDE256KL };
  { T::AESENC };
  { T::AESENC128KL };
  { T::AESENC256KL };
  { T::AESENCLAST };
  { T::AESENCWIDE128KL };
  { T::AESENCWIDE256KL };
  { T::AESIMC };
  { T::AESKEYGENASSIST };
  { T::AND };
  { T::ANDN };
  { T::ANDNPD };
  { T::ANDNPS };
  { T::ANDPD };
  { T::ANDPS };
  { T::AOR };
  { T::ARPL };
  { T::AXOR };
  { T::BEXTR };
  { T::BLCFILL };
  { T::BLCI };
  { T::BLCIC };
  { T::BLCMSK };
  { T::BLCS };
  { T::BLENDPD };
  { T::BLENDPS };
  { T::BLENDVPD };
  { T::BLENDVPS };
  { T::BLSFILL };
  { T::BLSI };
  { T::BLSIC };
  { T::BLSMSK };
  { T::BLSR };
  { T::BNDCL };
  { T::BNDCN };
  { T::BNDCU };
  { T::BNDLDX };
  { T::BNDMK };
  { T::BNDMOV };
  { T::BNDSTX };
  { T::BOUND };
  { T::BSF };
  { T::BSR };
  { T::BSWAP };
  { T::BT };
  { T::BTC };
  { T::BTR };
  { T::BTS };
  { T::BZHI };
  { T::CALL };
  // { T::CALL2 };
  { T::CBW };
  { T::CDQ };
  { T::CDQE };
  { T::CLAC };
  { T::CLC };
  { T::CLD };
  { T::CLDEMOTE };
  { T::CLEVICT0 };
  { T::CLEVICT1 };
  { T::CLFLUSH };
  { T::CLFLUSHOPT };
  { T::CLGI };
  { T::CLI };
  { T::CLRSSBSY };
  { T::CLTS };
  { T::CLUI };
  { T::CLWB };
  { T::CLZERO };
  { T::CMC };
  { T::CMOVB };
  { T::CMOVBE };
  { T::CMOVL };
  { T::CMOVLE };
  { T::CMOVNB };
  { T::CMOVNBE };
  { T::CMOVNL };
  { T::CMOVNLE };
  { T::CMOVNO };
  { T::CMOVNP };
  { T::CMOVNS };
  { T::CMOVNZ };
  { T::CMOVO };
  { T::CMOVP };
  { T::CMOVS };
  { T::CMOVZ };
  { T::CMP };
  { T::CMPPD };
  { T::CMPPS };
  { T::CMPSB };
  { T::CMPSD };
  { T::CMPSQ };
  { T::CMPSS };
  { T::CMPSW };
  { T::CMPXCHG };
  { T::CMPXCHG16B };
  { T::CMPXCHG8B };
  { T::COMISD };
  { T::COMISS };
  { T::CPUID };
  { T::CQO };
  { T::CRC32 };
  { T::CVTDQ2PD };
  { T::CVTDQ2PS };
  { T::CVTPD2DQ };
  { T::CVTPD2PI };
  { T::CVTPD2PS };
  { T::CVTPI2PD };
  { T::CVTPI2PS };
  { T::CVTPS2DQ };
  { T::CVTPS2PD };
  { T::CVTPS2PI };
  { T::CVTSD2SI };
  { T::CVTSD2SS };
  { T::CVTSI2SD };
  { T::CVTSI2SS };
  { T::CVTSS2SD };
  { T::CVTSS2SI };
  { T::CVTTPD2DQ };
  { T::CVTTPD2PI };
  { T::CVTTPS2DQ };
  { T::CVTTPS2PI };
  { T::CVTTSD2SI };
  { T::CVTTSS2SI };
  { T::CWD };
  { T::CWDE };
  { T::DAA };
  { T::DAS };
  { T::DEC };
  { T::DELAY };
  { T::DIV };
  { T::DIVPD };
  { T::DIVPS };
  { T::DIVSD };
  { T::DIVSS };
  { T::DPPD };
  { T::DPPS };
  { T::EMMS };
  { T::ENCLS };
  { T::ENCLU };
  { T::ENCLV };
  { T::ENCODEKEY128 };
  { T::ENCODEKEY256 };
  { T::ENDBR32 };
  { T::ENDBR64 };
  { T::ENQCMD };
  { T::ENQCMDS };
  { T::ENTER };
  { T::EXTRACTPS };
  { T::EXTRQ };
  { T::F2XM1 };
  { T::FABS };
  { T::FADD };
  { T::FADDP };
  { T::FBLD };
  { T::FBSTP };
  { T::FCHS };
  { T::FCMOVB };
  { T::FCMOVBE };
  { T::FCMOVE };
  { T::FCMOVNB };
  { T::FCMOVNBE };
  { T::FCMOVNE };
  { T::FCMOVNU };
  { T::FCMOVU };
  { T::FCOM };
  { T::FCOMI };
  { T::FCOMIP };
  { T::FCOMP };
  { T::FCOMPP };
  { T::FCOS };
  { T::FDECSTP };
  { T::FDISI8087_NOP };
  { T::FDIV };
  { T::FDIVP };
  { T::FDIVR };
  { T::FDIVRP };
  { T::FEMMS };
  { T::FENI8087_NOP };
  { T::FFREE };
  { T::FFREEP };
  { T::FIADD };
  { T::FICOM };
  { T::FICOMP };
  { T::FIDIV };
  { T::FIDIVR };
  { T::FILD };
  { T::FIMUL };
  { T::FINCSTP };
  { T::FIST };
  { T::FISTP };
  { T::FISTTP };
  { T::FISUB };
  { T::FISUBR };
  { T::FLD };
  { T::FLD1 };
  { T::FLDCW };
  { T::FLDENV };
  { T::FLDL2E };
  { T::FLDL2T };
  { T::FLDLG2 };
  { T::FLDLN2 };
  { T::FLDPI };
  { T::FLDZ };
  { T::FMUL };
  { T::FMULP };
  { T::FNCLEX };
  { T::FNINIT };
  { T::FNOP };
  { T::FNSAVE };
  { T::FNSTCW };
  { T::FNSTENV };
  { T::FNSTSW };
  { T::FPATAN };
  { T::FPREM };
  { T::FPREM1 };
  { T::FPTAN };
  { T::FRNDINT };
  { T::FRSTOR };
  { T::FSCALE };
  { T::FSETPM287_NOP };
  { T::FSIN };
  { T::FSINCOS };
  { T::FSQRT };
  { T::FST };
  { T::FSTP };
  { T::FSTPNCE };
  { T::FSUB };
  { T::FSUBP };
  { T::FSUBR };
  { T::FSUBRP };
  { T::FTST };
  { T::FUCOM };
  { T::FUCOMI };
  { T::FUCOMIP };
  { T::FUCOMP };
  { T::FUCOMPP };
  { T::FWAIT };
  { T::FXAM };
  { T::FXCH };
  { T::FXRSTOR };
  { T::FXRSTOR64 };
  { T::FXSAVE };
  { T::FXSAVE64 };
  { T::FXTRACT };
  { T::FYL2X };
  { T::FYL2XP1 };
  { T::GETSEC };
  { T::GF2P8AFFINEINVQB };
  { T::GF2P8AFFINEQB };
  { T::GF2P8MULB };
  { T::HADDPD };
  { T::HADDPS };
  { T::HLT };
  { T::HRESET };
  { T::HSUBPD };
  { T::HSUBPS };
  { T::IDIV };
  { T::IMUL };
  { T::IN };
  { T::INC };
  { T::INCSSPD };
  { T::INCSSPQ };
  { T::INSB };
  { T::INSD };
  { T::INSERTPS };
  { T::INSERTQ };
  { T::INSW };
  { T::INT };
  { T::INT1 };
  { T::INT3 };
  { T::INTO };
  { T::INVD };
  { T::INVEPT };
  { T::INVLPG };
  { T::INVLPGA };
  { T::INVLPGB };
  { T::INVPCID };
  { T::INVVPID };
  { T::IRET };
  { T::IRETD };
  { T::IRETQ };
  { T::JB };
  { T::JBE };
  { T::JCXZ };
  { T::JECXZ };
  { T::JKNZD };
  { T::JKZD };
  { T::JL };
  { T::JLE };
  { T::JMP };
  { T::JNB };
  { T::JNBE };
  { T::JNL };
  { T::JNLE };
  { T::JNO };
  { T::JNP };
  { T::JNS };
  { T::JNZ };
  { T::JO };
  { T::JP };
  { T::JRCXZ };
  { T::JS };
  { T::JZ };
  { T::KADDB };
  { T::KADDD };
  { T::KADDQ };
  { T::KADDW };
  { T::KAND };
  { T::KANDB };
  { T::KANDD };
  { T::KANDN };
  { T::KANDNB };
  { T::KANDND };
  { T::KANDNQ };
  { T::KANDNR };
  { T::KANDNW };
  { T::KANDQ };
  { T::KANDW };
  { T::KCONCATH };
  { T::KCONCATL };
  { T::KEXTRACT };
  { T::KMERGE2L1H };
  { T::KMERGE2L1L };
  { T::KMOV };
  { T::KMOVB };
  { T::KMOVD };
  { T::KMOVQ };
  { T::KMOVW };
  { T::KNOT };
  { T::KNOTB };
  { T::KNOTD };
  { T::KNOTQ };
  { T::KNOTW };
  { T::KOR };
  { T::KORB };
  { T::KORD };
  { T::KORQ };
  { T::KORTEST };
  { T::KORTESTB };
  { T::KORTESTD };
  { T::KORTESTQ };
  { T::KORTESTW };
  { T::KORW };
  { T::KSHIFTLB };
  { T::KSHIFTLD };
  { T::KSHIFTLQ };
  { T::KSHIFTLW };
  { T::KSHIFTRB };
  { T::KSHIFTRD };
  { T::KSHIFTRQ };
  { T::KSHIFTRW };
  { T::KTESTB };
  { T::KTESTD };
  { T::KTESTQ };
  { T::KTESTW };
  { T::KUNPCKBW };
  { T::KUNPCKDQ };
  { T::KUNPCKWD };
  { T::KXNOR };
  { T::KXNORB };
  { T::KXNORD };
  { T::KXNORQ };
  { T::KXNORW };
  { T::KXOR };
  { T::KXORB };
  { T::KXORD };
  { T::KXORQ };
  { T::KXORW };
  { T::LAHF };
  { T::LAR };
  { T::LDDQU };
  { T::LDMXCSR };
  { T::LDS };
  { T::LDTILECFG };
  { T::LEA };
  { T::LEAVE };
  { T::LES };
  { T::LFENCE };
  { T::LFS };
  { T::LGDT };
  { T::LGS };
  { T::LIDT };
  { T::LLDT };
  { T::LLWPCB };
  { T::LMSW };
  { T::LOADIWKEY };
  { T::LODSB };
  { T::LODSD };
  { T::LODSQ };
  { T::LODSW };
  { T::LOOP };
  { T::LOOPE };
  { T::LOOPNE };
  { T::LSL };
  { T::LSS };
  { T::LTR };
  { T::LWPINS };
  { T::LWPVAL };
  { T::LZCNT };
  { T::MASKMOVDQU };
  { T::MASKMOVQ };
  { T::MAXPD };
  { T::MAXPS };
  { T::MAXSD };
  { T::MAXSS };
  { T::MCOMMIT };
  { T::MFENCE };
  { T::MINPD };
  { T::MINPS };
  { T::MINSD };
  { T::MINSS };
  { T::MONITOR };
  { T::MONITORX };
  { T::MONTMUL };
  { T::MOV };
  { T::MOVAPD };
  { T::MOVAPS };
  { T::MOVBE };
  { T::MOVD };
  { T::MOVDDUP };
  { T::MOVDIR64B };
  { T::MOVDIRI };
  { T::MOVDQ2Q };
  { T::MOVDQA };
  { T::MOVDQU };
  { T::MOVHLPS };
  { T::MOVHPD };
  { T::MOVHPS };
  { T::MOVLHPS };
  { T::MOVLPD };
  { T::MOVLPS };
  { T::MOVMSKPD };
  { T::MOVMSKPS };
  { T::MOVNTDQ };
  { T::MOVNTDQA };
  { T::MOVNTI };
  { T::MOVNTPD };
  { T::MOVNTPS };
  { T::MOVNTQ };
  { T::MOVNTSD };
  { T::MOVNTSS };
  { T::MOVQ };
  { T::MOVQ2DQ };
  { T::MOVSB };
  { T::MOVSD };
  { T::MOVSHDUP };
  { T::MOVSLDUP };
  { T::MOVSQ };
  { T::MOVSS };
  { T::MOVSW };
  { T::MOVSX };
  { T::MOVSXD };
  { T::MOVUPD };
  { T::MOVUPS };
  { T::MOVZX };
  { T::MPSADBW };
  { T::MUL };
  { T::MULPD };
  { T::MULPS };
  { T::MULSD };
  { T::MULSS };
  { T::MULX };
  { T::MWAIT };
  { T::MWAITX };
  { T::NEG };
  { T::NOP };
  { T::NOT };
  { T::OR };
  { T::ORPD };
  { T::ORPS };
  { T::OUT };
  { T::OUTSB };
  { T::OUTSD };
  { T::OUTSW };
  { T::PABSB };
  { T::PABSD };
  { T::PABSW };
  { T::PACKSSDW };
  { T::PACKSSWB };
  { T::PACKUSDW };
  { T::PACKUSWB };
  { T::PADDB };
  { T::PADDD };
  { T::PADDQ };
  { T::PADDSB };
  { T::PADDSW };
  { T::PADDUSB };
  { T::PADDUSW };
  { T::PADDW };
  { T::PALIGNR };
  { T::PAND };
  { T::PANDN };
  { T::PAUSE };
  { T::PAVGB };
  { T::PAVGUSB };
  { T::PAVGW };
  { T::PBLENDVB };
  { T::PBLENDW };
  { T::PBNDKB };
  { T::PCLMULQDQ };
  { T::PCMPEQB };
  { T::PCMPEQD };
  { T::PCMPEQQ };
  { T::PCMPEQW };
  { T::PCMPESTRI };
  { T::PCMPESTRM };
  { T::PCMPGTB };
  { T::PCMPGTD };
  { T::PCMPGTQ };
  { T::PCMPGTW };
  { T::PCMPISTRI };
  { T::PCMPISTRM };
  { T::PCOMMIT };
  { T::PCONFIG };
  { T::PDEP };
  { T::PEXT };
  { T::PEXTRB };
  { T::PEXTRD };
  { T::PEXTRQ };
  { T::PEXTRW };
  { T::PF2ID };
  { T::PF2IW };
  { T::PFACC };
  { T::PFADD };
  { T::PFCMPEQ };
  { T::PFCMPGE };
  { T::PFCMPGT };
  { T::PFCPIT1 };
  { T::PFMAX };
  { T::PFMIN };
  { T::PFMUL };
  { T::PFNACC };
  { T::PFPNACC };
  { T::PFRCP };
  { T::PFRCPIT2 };
  { T::PFRSQIT1 };
  { T::PFSQRT };
  { T::PFSUB };
  { T::PFSUBR };
  { T::PHADDD };
  { T::PHADDSW };
  { T::PHADDW };
  { T::PHMINPOSUW };
  { T::PHSUBD };
  { T::PHSUBSW };
  { T::PHSUBW };
  { T::PI2FD };
  { T::PI2FW };
  { T::PINSRB };
  { T::PINSRD };
  { T::PINSRQ };
  { T::PINSRW };
  { T::PMADDUBSW };
  { T::PMADDWD };
  { T::PMAXSB };
  { T::PMAXSD };
  { T::PMAXSW };
  { T::PMAXUB };
  { T::PMAXUD };
  { T::PMAXUW };
  { T::PMINSB };
  { T::PMINSD };
  { T::PMINSW };
  { T::PMINUB };
  { T::PMINUD };
  { T::PMINUW };
  { T::PMOVMSKB };
  { T::PMOVSXBD };
  { T::PMOVSXBQ };
  { T::PMOVSXBW };
  { T::PMOVSXDQ };
  { T::PMOVSXWD };
  { T::PMOVSXWQ };
  { T::PMOVZXBD };
  { T::PMOVZXBQ };
  { T::PMOVZXBW };
  { T::PMOVZXDQ };
  { T::PMOVZXWD };
  { T::PMOVZXWQ };
  { T::PMULDQ };
  { T::PMULHRSW };
  { T::PMULHRW };
  { T::PMULHUW };
  { T::PMULHW };
  { T::PMULLD };
  { T::PMULLW };
  { T::PMULUDQ };
  { T::POP };
  { T::POPA };
  { T::POPAD };
  { T::POPCNT };
  { T::POPF };
  { T::POPFD };
  { T::POPFQ };
  { T::POR };
  { T::PREFETCH };
  { T::PREFETCHIT0 };
  { T::PREFETCHIT1 };
  { T::PREFETCHNTA };
  { T::PREFETCHT0 };
  { T::PREFETCHT1 };
  { T::PREFETCHT2 };
  { T::PREFETCHW };
  { T::PREFETCHWT1 };
  { T::PSADBW };
  { T::PSHUFB };
  { T::PSHUFD };
  { T::PSHUFHW };
  { T::PSHUFLW };
  { T::PSHUFW };
  { T::PSIGNB };
  { T::PSIGND };
  { T::PSIGNW };
  { T::PSLLD };
  { T::PSLLDQ };
  { T::PSLLQ };
  { T::PSLLW };
  { T::PSMASH };
  { T::PSRAD };
  { T::PSRAW };
  { T::PSRLD };
  { T::PSRLDQ };
  { T::PSRLQ };
  { T::PSRLW };
  { T::PSUBB };
  { T::PSUBD };
  { T::PSUBQ };
  { T::PSUBSB };
  { T::PSUBSW };
  { T::PSUBUSB };
  { T::PSUBUSW };
  { T::PSUBW };
  { T::PSWAPD };
  { T::PTEST };
  { T::PTWRITE };
  { T::PUNPCKHBW };
  { T::PUNPCKHDQ };
  { T::PUNPCKHQDQ };
  { T::PUNPCKHWD };
  { T::PUNPCKLBW };
  { T::PUNPCKLDQ };
  { T::PUNPCKLQDQ };
  { T::PUNPCKLWD };
  { T::PUSH };
  { T::PUSHA };
  { T::PUSHAD };
  { T::PUSHF };
  { T::PUSHFD };
  { T::PUSHFQ };
  { T::PVALIDATE };
  { T::PXOR };
  { T::RCL };
  { T::RCPPS };
  { T::RCPSS };
  { T::RCR };
  { T::RDFSBASE };
  { T::RDGSBASE };
  { T::RDMSR };
  { T::RDMSRLIST };
  { T::RDPID };
  { T::RDPKRU };
  { T::RDPMC };
  { T::RDPRU };
  { T::RDRAND };
  { T::RDSEED };
  { T::RDSSPD };
  { T::RDSSPQ };
  { T::RDTSC };
  { T::RDTSCP };
  { T::RET };
  { T::RMPADJUST };
  { T::RMPUPDATE };
  { T::ROL };
  { T::ROR };
  { T::RORX };
  { T::ROUNDPD };
  { T::ROUNDPS };
  { T::ROUNDSD };
  { T::ROUNDSS };
  { T::RSM };
  { T::RSQRTPS };
  { T::RSQRTSS };
  { T::RSTORSSP };
  { T::SAHF };
  { T::SALC };
  { T::SAR };
  { T::SARX };
  { T::SAVEPREVSSP };
  { T::SBB };
  { T::SCASB };
  { T::SCASD };
  { T::SCASQ };
  { T::SCASW };
  { T::SEAMCALL };
  { T::SEAMOPS };
  { T::SEAMRET };
  { T::SENDUIPI };
  { T::SERIALIZE };
  { T::SETB };
  { T::SETBE };
  { T::SETL };
  { T::SETLE };
  { T::SETNB };
  { T::SETNBE };
  { T::SETNL };
  { T::SETNLE };
  { T::SETNO };
  { T::SETNP };
  { T::SETNS };
  { T::SETNZ };
  { T::SETO };
  { T::SETP };
  { T::SETS };
  { T::SETSSBSY };
  { T::SETZ };
  { T::SFENCE };
  { T::SGDT };
  { T::SHA1MSG1 };
  { T::SHA1MSG2 };
  { T::SHA1NEXTE };
  { T::SHA1RNDS4 };
  { T::SHA256MSG1 };
  { T::SHA256MSG2 };
  { T::SHA256RNDS2 };
  { T::SAL };
  { T::SHL };
  { T::SHLD };
  { T::SHLX };
  { T::SHR };
  { T::SHRD };
  { T::SHRX };
  { T::SHUFPD };
  { T::SHUFPS };
  { T::SIDT };
  { T::SKINIT };
  { T::SLDT };
  { T::SLWPCB };
  { T::SMSW };
  { T::SPFLT };
  { T::SQRTPD };
  { T::SQRTPS };
  { T::SQRTSD };
  { T::SQRTSS };
  { T::STAC };
  { T::STC };
  { T::STD };
  { T::STGI };
  { T::STI };
  { T::STMXCSR };
  { T::STOSB };
  { T::STOSD };
  { T::STOSQ };
  { T::STOSW };
  { T::STR };
  { T::STTILECFG };
  { T::STUI };
  { T::SUB };
  { T::SUBPD };
  { T::SUBPS };
  { T::SUBSD };
  { T::SUBSS };
  { T::SWAPGS };
  { T::SYSCALL };
  { T::SYSENTER };
  { T::SYSEXIT };
  { T::SYSRET };
  { T::T1MSKC };
  { T::TDCALL };
  { T::TDPBF16PS };
  { T::TDPBSSD };
  { T::TDPBSUD };
  { T::TDPBUSD };
  { T::TDPBUUD };
  { T::TDPFP16PS };
  { T::TEST };
  { T::TESTUI };
  { T::TILELOADD };
  { T::TILELOADDT1 };
  { T::TILERELEASE };
  { T::TILESTORED };
  { T::TILEZERO };
  { T::TLBSYNC };
  { T::TPAUSE };
  { T::TZCNT };
  { T::TZCNTI };
  { T::TZMSK };
  { T::UCOMISD };
  { T::UCOMISS };
  { T::UD0 };
  { T::UD1 };
  { T::UD2 };
  { T::UIRET };
  { T::UMONITOR };
  { T::UMWAIT };
  { T::UNPCKHPD };
  { T::UNPCKHPS };
  { T::UNPCKLPD };
  { T::UNPCKLPS };
  { T::V4FMADDPS };
  { T::V4FMADDSS };
  { T::V4FNMADDPS };
  { T::V4FNMADDSS };
  { T::VADDNPD };
  { T::VADDNPS };
  { T::VADDPD };
  { T::VADDPH };
  { T::VADDPS };
  { T::VADDSD };
  { T::VADDSETSPS };
  { T::VADDSH };
  { T::VADDSS };
  { T::VADDSUBPD };
  { T::VADDSUBPS };
  { T::VAESDEC };
  { T::VAESDECLAST };
  { T::VAESENC };
  { T::VAESENCLAST };
  { T::VAESIMC };
  { T::VAESKEYGENASSIST };
  { T::VALIGND };
  { T::VALIGNQ };
  { T::VANDNPD };
  { T::VANDNPS };
  { T::VANDPD };
  { T::VANDPS };
  { T::VBCSTNEBF162PS };
  { T::VBCSTNESH2PS };
  { T::VBLENDMPD };
  { T::VBLENDMPS };
  { T::VBLENDPD };
  { T::VBLENDPS };
  { T::VBLENDVPD };
  { T::VBLENDVPS };
  { T::VBROADCASTF128 };
  { T::VBROADCASTF32X2 };
  { T::VBROADCASTF32X4 };
  { T::VBROADCASTF32X8 };
  { T::VBROADCASTF64X2 };
  { T::VBROADCASTF64X4 };
  { T::VBROADCASTI128 };
  { T::VBROADCASTI32X2 };
  { T::VBROADCASTI32X4 };
  { T::VBROADCASTI32X8 };
  { T::VBROADCASTI64X2 };
  { T::VBROADCASTI64X4 };
  { T::VBROADCASTSD };
  { T::VBROADCASTSS };
  { T::VCMPPD };
  { T::VCMPPH };
  { T::VCMPPS };
  { T::VCMPSD };
  { T::VCMPSH };
  { T::VCMPSS };
  { T::VCOMISD };
  { T::VCOMISH };
  { T::VCOMISS };
  { T::VCOMPRESSPD };
  { T::VCOMPRESSPS };
  { T::VCVTDQ2PD };
  { T::VCVTDQ2PH };
  { T::VCVTDQ2PS };
  { T::VCVTFXPNTDQ2PS };
  { T::VCVTFXPNTPD2DQ };
  { T::VCVTFXPNTPD2UDQ };
  { T::VCVTFXPNTPS2DQ };
  { T::VCVTFXPNTPS2UDQ };
  { T::VCVTFXPNTUDQ2PS };
  { T::VCVTNE2PS2BF16 };
  { T::VCVTNEEBF162PS };
  { T::VCVTNEEPH2PS };
  { T::VCVTNEOBF162PS };
  { T::VCVTNEOPH2PS };
  { T::VCVTNEPS2BF16 };
  { T::VCVTPD2DQ };
  { T::VCVTPD2PH };
  { T::VCVTPD2PS };
  { T::VCVTPD2QQ };
  { T::VCVTPD2UDQ };
  { T::VCVTPD2UQQ };
  { T::VCVTPH2DQ };
  { T::VCVTPH2PD };
  { T::VCVTPH2PS };
  { T::VCVTPH2PSX };
  { T::VCVTPH2QQ };
  { T::VCVTPH2UDQ };
  { T::VCVTPH2UQQ };
  { T::VCVTPH2UW };
  { T::VCVTPH2W };
  { T::VCVTPS2DQ };
  { T::VCVTPS2PD };
  { T::VCVTPS2PH };
  { T::VCVTPS2PHX };
  { T::VCVTPS2QQ };
  { T::VCVTPS2UDQ };
  { T::VCVTPS2UQQ };
  { T::VCVTQQ2PD };
  { T::VCVTQQ2PH };
  { T::VCVTQQ2PS };
  { T::VCVTSD2SH };
  { T::VCVTSD2SI };
  { T::VCVTSD2SS };
  { T::VCVTSD2USI };
  { T::VCVTSH2SD };
  { T::VCVTSH2SI };
  { T::VCVTSH2SS };
  { T::VCVTSH2USI };
  { T::VCVTSI2SD };
  { T::VCVTSI2SH };
  { T::VCVTSI2SS };
  { T::VCVTSS2SD };
  { T::VCVTSS2SH };
  { T::VCVTSS2SI };
  { T::VCVTSS2USI };
  { T::VCVTTPD2DQ };
  { T::VCVTTPD2QQ };
  { T::VCVTTPD2UDQ };
  { T::VCVTTPD2UQQ };
  { T::VCVTTPH2DQ };
  { T::VCVTTPH2QQ };
  { T::VCVTTPH2UDQ };
  { T::VCVTTPH2UQQ };
  { T::VCVTTPH2UW };
  { T::VCVTTPH2W };
  { T::VCVTTPS2DQ };
  { T::VCVTTPS2QQ };
  { T::VCVTTPS2UDQ };
  { T::VCVTTPS2UQQ };
  { T::VCVTTSD2SI };
  { T::VCVTTSD2USI };
  { T::VCVTTSH2SI };
  { T::VCVTTSH2USI };
  { T::VCVTTSS2SI };
  { T::VCVTTSS2USI };
  { T::VCVTUDQ2PD };
  { T::VCVTUDQ2PH };
  { T::VCVTUDQ2PS };
  { T::VCVTUQQ2PD };
  { T::VCVTUQQ2PH };
  { T::VCVTUQQ2PS };
  { T::VCVTUSI2SD };
  { T::VCVTUSI2SH };
  { T::VCVTUSI2SS };
  { T::VCVTUW2PH };
  { T::VCVTW2PH };
  { T::VDBPSADBW };
  { T::VDIVPD };
  { T::VDIVPH };
  { T::VDIVPS };
  { T::VDIVSD };
  { T::VDIVSH };
  { T::VDIVSS };
  { T::VDPBF16PS };
  { T::VDPPD };
  { T::VDPPS };
  { T::VERR };
  { T::VERW };
  { T::VEXP223PS };
  { T::VEXP2PD };
  { T::VEXP2PS };
  { T::VEXPANDPD };
  { T::VEXPANDPS };
  { T::VEXTRACTF128 };
  { T::VEXTRACTF32X4 };
  { T::VEXTRACTF32X8 };
  { T::VEXTRACTF64X2 };
  { T::VEXTRACTF64X4 };
  { T::VEXTRACTI128 };
  { T::VEXTRACTI32X4 };
  { T::VEXTRACTI32X8 };
  { T::VEXTRACTI64X2 };
  { T::VEXTRACTI64X4 };
  { T::VEXTRACTPS };
  { T::VFCMADDCPH };
  { T::VFCMADDCSH };
  { T::VFCMULCPH };
  { T::VFCMULCSH };
  { T::VFIXUPIMMPD };
  { T::VFIXUPIMMPS };
  { T::VFIXUPIMMSD };
  { T::VFIXUPIMMSS };
  { T::VFIXUPNANPD };
  { T::VFIXUPNANPS };
  { T::VFMADD132PD };
  { T::VFMADD132PH };
  { T::VFMADD132PS };
  { T::VFMADD132SD };
  { T::VFMADD132SH };
  { T::VFMADD132SS };
  { T::VFMADD213PD };
  { T::VFMADD213PH };
  { T::VFMADD213PS };
  { T::VFMADD213SD };
  { T::VFMADD213SH };
  { T::VFMADD213SS };
  { T::VFMADD231PD };
  { T::VFMADD231PH };
  { T::VFMADD231PS };
  { T::VFMADD231SD };
  { T::VFMADD231SH };
  { T::VFMADD231SS };
  { T::VFMADD233PS };
  { T::VFMADDCPH };
  { T::VFMADDCSH };
  { T::VFMADDPD };
  { T::VFMADDPS };
  { T::VFMADDSD };
  { T::VFMADDSS };
  { T::VFMADDSUB132PD };
  { T::VFMADDSUB132PH };
  { T::VFMADDSUB132PS };
  { T::VFMADDSUB213PD };
  { T::VFMADDSUB213PH };
  { T::VFMADDSUB213PS };
  { T::VFMADDSUB231PD };
  { T::VFMADDSUB231PH };
  { T::VFMADDSUB231PS };
  { T::VFMADDSUBPD };
  { T::VFMADDSUBPS };
  { T::VFMSUB132PD };
  { T::VFMSUB132PH };
  { T::VFMSUB132PS };
  { T::VFMSUB132SD };
  { T::VFMSUB132SH };
  { T::VFMSUB132SS };
  { T::VFMSUB213PD };
  { T::VFMSUB213PH };
  { T::VFMSUB213PS };
  { T::VFMSUB213SD };
  { T::VFMSUB213SH };
  { T::VFMSUB213SS };
  { T::VFMSUB231PD };
  { T::VFMSUB231PH };
  { T::VFMSUB231PS };
  { T::VFMSUB231SD };
  { T::VFMSUB231SH };
  { T::VFMSUB231SS };
  { T::VFMSUBADD132PD };
  { T::VFMSUBADD132PH };
  { T::VFMSUBADD132PS };
  { T::VFMSUBADD213PD };
  { T::VFMSUBADD213PH };
  { T::VFMSUBADD213PS };
  { T::VFMSUBADD231PD };
  { T::VFMSUBADD231PH };
  { T::VFMSUBADD231PS };
  { T::VFMSUBADDPD };
  { T::VFMSUBADDPS };
  { T::VFMSUBPD };
  { T::VFMSUBPS };
  { T::VFMSUBSD };
  { T::VFMSUBSS };
  { T::VFMULCPH };
  { T::VFMULCSH };
  { T::VFNMADD132PD };
  { T::VFNMADD132PH };
  { T::VFNMADD132PS };
  { T::VFNMADD132SD };
  { T::VFNMADD132SH };
  { T::VFNMADD132SS };
  { T::VFNMADD213PD };
  { T::VFNMADD213PH };
  { T::VFNMADD213PS };
  { T::VFNMADD213SD };
  { T::VFNMADD213SH };
  { T::VFNMADD213SS };
  { T::VFNMADD231PD };
  { T::VFNMADD231PH };
  { T::VFNMADD231PS };
  { T::VFNMADD231SD };
  { T::VFNMADD231SH };
  { T::VFNMADD231SS };
  { T::VFNMADDPD };
  { T::VFNMADDPS };
  { T::VFNMADDSD };
  { T::VFNMADDSS };
  { T::VFNMSUB132PD };
  { T::VFNMSUB132PH };
  { T::VFNMSUB132PS };
  { T::VFNMSUB132SD };
  { T::VFNMSUB132SH };
  { T::VFNMSUB132SS };
  { T::VFNMSUB213PD };
  { T::VFNMSUB213PH };
  { T::VFNMSUB213PS };
  { T::VFNMSUB213SD };
  { T::VFNMSUB213SH };
  { T::VFNMSUB213SS };
  { T::VFNMSUB231PD };
  { T::VFNMSUB231PH };
  { T::VFNMSUB231PS };
  { T::VFNMSUB231SD };
  { T::VFNMSUB231SH };
  { T::VFNMSUB231SS };
  { T::VFNMSUBPD };
  { T::VFNMSUBPS };
  { T::VFNMSUBSD };
  { T::VFNMSUBSS };
  { T::VFPCLASSPD };
  { T::VFPCLASSPH };
  { T::VFPCLASSPS };
  { T::VFPCLASSSD };
  { T::VFPCLASSSH };
  { T::VFPCLASSSS };
  { T::VFRCZPD };
  { T::VFRCZPS };
  { T::VFRCZSD };
  { T::VFRCZSS };
  { T::VGATHERDPD };
  { T::VGATHERDPS };
  { T::VGATHERPF0DPD };
  { T::VGATHERPF0DPS };
  { T::VGATHERPF0HINTDPD };
  { T::VGATHERPF0HINTDPS };
  { T::VGATHERPF0QPD };
  { T::VGATHERPF0QPS };
  { T::VGATHERPF1DPD };
  { T::VGATHERPF1DPS };
  { T::VGATHERPF1QPD };
  { T::VGATHERPF1QPS };
  { T::VGATHERQPD };
  { T::VGATHERQPS };
  { T::VGETEXPPD };
  { T::VGETEXPPH };
  { T::VGETEXPPS };
  { T::VGETEXPSD };
  { T::VGETEXPSH };
  { T::VGETEXPSS };
  { T::VGETMANTPD };
  { T::VGETMANTPH };
  { T::VGETMANTPS };
  { T::VGETMANTSD };
  { T::VGETMANTSH };
  { T::VGETMANTSS };
  { T::VGF2P8AFFINEINVQB };
  { T::VGF2P8AFFINEQB };
  { T::VGF2P8MULB };
  { T::VGMAXABSPS };
  { T::VGMAXPD };
  { T::VGMAXPS };
  { T::VGMINPD };
  { T::VGMINPS };
  { T::VHADDPD };
  { T::VHADDPS };
  { T::VHSUBPD };
  { T::VHSUBPS };
  { T::VINSERTF128 };
  { T::VINSERTF32X4 };
  { T::VINSERTF32X8 };
  { T::VINSERTF64X2 };
  { T::VINSERTF64X4 };
  { T::VINSERTI128 };
  { T::VINSERTI32X4 };
  { T::VINSERTI32X8 };
  { T::VINSERTI64X2 };
  { T::VINSERTI64X4 };
  { T::VINSERTPS };
  { T::VLDDQU };
  { T::VLDMXCSR };
  { T::VLOADUNPACKHD };
  { T::VLOADUNPACKHPD };
  { T::VLOADUNPACKHPS };
  { T::VLOADUNPACKHQ };
  { T::VLOADUNPACKLD };
  { T::VLOADUNPACKLPD };
  { T::VLOADUNPACKLPS };
  { T::VLOADUNPACKLQ };
  { T::VLOG2PS };
  { T::VMASKMOVDQU };
  { T::VMASKMOVPD };
  { T::VMASKMOVPS };
  { T::VMAXPD };
  { T::VMAXPH };
  { T::VMAXPS };
  { T::VMAXSD };
  { T::VMAXSH };
  { T::VMAXSS };
  { T::VMCALL };
  { T::VMCLEAR };
  { T::VMFUNC };
  { T::VMINPD };
  { T::VMINPH };
  { T::VMINPS };
  { T::VMINSD };
  { T::VMINSH };
  { T::VMINSS };
  { T::VMLAUNCH };
  { T::VMLOAD };
  { T::VMMCALL };
  { T::VMOVAPD };
  { T::VMOVAPS };
  { T::VMOVD };
  { T::VMOVDDUP };
  { T::VMOVDQA };
  { T::VMOVDQA32 };
  { T::VMOVDQA64 };
  { T::VMOVDQU };
  { T::VMOVDQU16 };
  { T::VMOVDQU32 };
  { T::VMOVDQU64 };
  { T::VMOVDQU8 };
  { T::VMOVHLPS };
  { T::VMOVHPD };
  { T::VMOVHPS };
  { T::VMOVLHPS };
  { T::VMOVLPD };
  { T::VMOVLPS };
  { T::VMOVMSKPD };
  { T::VMOVMSKPS };
  { T::VMOVNRAPD };
  { T::VMOVNRAPS };
  { T::VMOVNRNGOAPD };
  { T::VMOVNRNGOAPS };
  { T::VMOVNTDQ };
  { T::VMOVNTDQA };
  { T::VMOVNTPD };
  { T::VMOVNTPS };
  { T::VMOVQ };
  { T::VMOVSD };
  { T::VMOVSH };
  { T::VMOVSHDUP };
  { T::VMOVSLDUP };
  { T::VMOVSS };
  { T::VMOVUPD };
  { T::VMOVUPS };
  { T::VMOVW };
  { T::VMPSADBW };
  { T::VMPTRLD };
  { T::VMPTRST };
  { T::VMREAD };
  { T::VMRESUME };
  { T::VMRUN };
  { T::VMSAVE };
  { T::VMULPD };
  { T::VMULPH };
  { T::VMULPS };
  { T::VMULSD };
  { T::VMULSH };
  { T::VMULSS };
  { T::VMWRITE };
  { T::VMXOFF };
  { T::VMXON };
  { T::VORPD };
  { T::VORPS };
  { T::VP2INTERSECTD };
  { T::VP2INTERSECTQ };
  { T::VP4DPWSSD };
  { T::VP4DPWSSDS };
  { T::VPABSB };
  { T::VPABSD };
  { T::VPABSQ };
  { T::VPABSW };
  { T::VPACKSSDW };
  { T::VPACKSSWB };
  { T::VPACKSTOREHD };
  { T::VPACKSTOREHPD };
  { T::VPACKSTOREHPS };
  { T::VPACKSTOREHQ };
  { T::VPACKSTORELD };
  { T::VPACKSTORELPD };
  { T::VPACKSTORELPS };
  { T::VPACKSTORELQ };
  { T::VPACKUSDW };
  { T::VPACKUSWB };
  { T::VPADCD };
  { T::VPADDB };
  { T::VPADDD };
  { T::VPADDQ };
  { T::VPADDSB };
  { T::VPADDSETCD };
  { T::VPADDSETSD };
  { T::VPADDSW };
  { T::VPADDUSB };
  { T::VPADDUSW };
  { T::VPADDW };
  { T::VPALIGNR };
  { T::VPAND };
  { T::VPANDD };
  { T::VPANDN };
  { T::VPANDND };
  { T::VPANDNQ };
  { T::VPANDQ };
  { T::VPAVGB };
  { T::VPAVGW };
  { T::VPBLENDD };
  { T::VPBLENDMB };
  { T::VPBLENDMD };
  { T::VPBLENDMQ };
  { T::VPBLENDMW };
  { T::VPBLENDVB };
  { T::VPBLENDW };
  { T::VPBROADCASTB };
  { T::VPBROADCASTD };
  { T::VPBROADCASTMB2Q };
  { T::VPBROADCASTMW2D };
  { T::VPBROADCASTQ };
  { T::VPBROADCASTW };
  { T::VPCLMULQDQ };
  { T::VPCMOV };
  { T::VPCMPB };
  { T::VPCMPD };
  { T::VPCMPEQB };
  { T::VPCMPEQD };
  { T::VPCMPEQQ };
  { T::VPCMPEQW };
  { T::VPCMPESTRI };
  { T::VPCMPESTRM };
  { T::VPCMPGTB };
  { T::VPCMPGTD };
  { T::VPCMPGTQ };
  { T::VPCMPGTW };
  { T::VPCMPISTRI };
  { T::VPCMPISTRM };
  { T::VPCMPLTD };
  { T::VPCMPQ };
  { T::VPCMPUB };
  { T::VPCMPUD };
  { T::VPCMPUQ };
  { T::VPCMPUW };
  { T::VPCMPW };
  { T::VPCOMB };
  { T::VPCOMD };
  { T::VPCOMPRESSB };
  { T::VPCOMPRESSD };
  { T::VPCOMPRESSQ };
  { T::VPCOMPRESSW };
  { T::VPCOMQ };
  { T::VPCOMUB };
  { T::VPCOMUD };
  { T::VPCOMUQ };
  { T::VPCOMUW };
  { T::VPCOMW };
  { T::VPCONFLICTD };
  { T::VPCONFLICTQ };
  { T::VPDPBSSD };
  { T::VPDPBSSDS };
  { T::VPDPBSUD };
  { T::VPDPBSUDS };
  { T::VPDPBUSD };
  { T::VPDPBUSDS };
  { T::VPDPBUUD };
  { T::VPDPBUUDS };
  { T::VPDPWSSD };
  { T::VPDPWSSDS };
  { T::VPDPWSUD };
  { T::VPDPWSUDS };
  { T::VPDPWUSD };
  { T::VPDPWUSDS };
  { T::VPDPWUUD };
  { T::VPDPWUUDS };
  { T::VPERM2F128 };
  { T::VPERM2I128 };
  { T::VPERMB };
  { T::VPERMD };
  { T::VPERMF32X4 };
  { T::VPERMI2B };
  { T::VPERMI2D };
  { T::VPERMI2PD };
  { T::VPERMI2PS };
  { T::VPERMI2Q };
  { T::VPERMI2W };
  { T::VPERMIL2PD };
  { T::VPERMIL2PS };
  { T::VPERMILPD };
  { T::VPERMILPS };
  { T::VPERMPD };
  { T::VPERMPS };
  { T::VPERMQ };
  { T::VPERMT2B };
  { T::VPERMT2D };
  { T::VPERMT2PD };
  { T::VPERMT2PS };
  { T::VPERMT2Q };
  { T::VPERMT2W };
  { T::VPERMW };
  { T::VPEXPANDB };
  { T::VPEXPANDD };
  { T::VPEXPANDQ };
  { T::VPEXPANDW };
  { T::VPEXTRB };
  { T::VPEXTRD };
  { T::VPEXTRQ };
  { T::VPEXTRW };
  { T::VPGATHERDD };
  { T::VPGATHERDQ };
  { T::VPGATHERQD };
  { T::VPGATHERQQ };
  { T::VPHADDBD };
  { T::VPHADDBQ };
  { T::VPHADDBW };
  { T::VPHADDD };
  { T::VPHADDDQ };
  { T::VPHADDSW };
  { T::VPHADDUBD };
  { T::VPHADDUBQ };
  { T::VPHADDUBW };
  { T::VPHADDUDQ };
  { T::VPHADDUWD };
  { T::VPHADDUWQ };
  { T::VPHADDW };
  { T::VPHADDWD };
  { T::VPHADDWQ };
  { T::VPHMINPOSUW };
  { T::VPHSUBBW };
  { T::VPHSUBD };
  { T::VPHSUBDQ };
  { T::VPHSUBSW };
  { T::VPHSUBW };
  { T::VPHSUBWD };
  { T::VPINSRB };
  { T::VPINSRD };
  { T::VPINSRQ };
  { T::VPINSRW };
  { T::VPLZCNTD };
  { T::VPLZCNTQ };
  { T::VPMACSDD };
  { T::VPMACSDQH };
  { T::VPMACSDQL };
  { T::VPMACSSDD };
  { T::VPMACSSDQH };
  { T::VPMACSSDQL };
  { T::VPMACSSWD };
  { T::VPMACSSWW };
  { T::VPMACSWD };
  { T::VPMACSWW };
  { T::VPMADCSSWD };
  { T::VPMADCSWD };
  { T::VPMADD231D };
  { T::VPMADD233D };
  { T::VPMADD52HUQ };
  { T::VPMADD52LUQ };
  { T::VPMADDUBSW };
  { T::VPMADDWD };
  { T::VPMASKMOVD };
  { T::VPMASKMOVQ };
  { T::VPMAXSB };
  { T::VPMAXSD };
  { T::VPMAXSQ };
  { T::VPMAXSW };
  { T::VPMAXUB };
  { T::VPMAXUD };
  { T::VPMAXUQ };
  { T::VPMAXUW };
  { T::VPMINSB };
  { T::VPMINSD };
  { T::VPMINSQ };
  { T::VPMINSW };
  { T::VPMINUB };
  { T::VPMINUD };
  { T::VPMINUQ };
  { T::VPMINUW };
  { T::VPMOVB2M };
  { T::VPMOVD2M };
  { T::VPMOVDB };
  { T::VPMOVDW };
  { T::VPMOVM2B };
  { T::VPMOVM2D };
  { T::VPMOVM2Q };
  { T::VPMOVM2W };
  { T::VPMOVMSKB };
  { T::VPMOVQ2M };
  { T::VPMOVQB };
  { T::VPMOVQD };
  { T::VPMOVQW };
  { T::VPMOVSDB };
  { T::VPMOVSDW };
  { T::VPMOVSQB };
  { T::VPMOVSQD };
  { T::VPMOVSQW };
  { T::VPMOVSWB };
  { T::VPMOVSXBD };
  { T::VPMOVSXBQ };
  { T::VPMOVSXBW };
  { T::VPMOVSXDQ };
  { T::VPMOVSXWD };
  { T::VPMOVSXWQ };
  { T::VPMOVUSDB };
  { T::VPMOVUSDW };
  { T::VPMOVUSQB };
  { T::VPMOVUSQD };
  { T::VPMOVUSQW };
  { T::VPMOVUSWB };
  { T::VPMOVW2M };
  { T::VPMOVWB };
  { T::VPMOVZXBD };
  { T::VPMOVZXBQ };
  { T::VPMOVZXBW };
  { T::VPMOVZXDQ };
  { T::VPMOVZXWD };
  { T::VPMOVZXWQ };
  { T::VPMULDQ };
  { T::VPMULHD };
  { T::VPMULHRSW };
  { T::VPMULHUD };
  { T::VPMULHUW };
  { T::VPMULHW };
  { T::VPMULLD };
  { T::VPMULLQ };
  { T::VPMULLW };
  { T::VPMULTISHIFTQB };
  { T::VPMULUDQ };
  { T::VPOPCNTB };
  { T::VPOPCNTD };
  { T::VPOPCNTQ };
  { T::VPOPCNTW };
  { T::VPOR };
  { T::VPORD };
  { T::VPORQ };
  { T::VPPERM };
  { T::VPREFETCH0 };
  { T::VPREFETCH1 };
  { T::VPREFETCH2 };
  { T::VPREFETCHE0 };
  { T::VPREFETCHE1 };
  { T::VPREFETCHE2 };
  { T::VPREFETCHENTA };
  { T::VPREFETCHNTA };
  { T::VPROLD };
  { T::VPROLQ };
  { T::VPROLVD };
  { T::VPROLVQ };
  { T::VPRORD };
  { T::VPRORQ };
  { T::VPRORVD };
  { T::VPRORVQ };
  { T::VPROTB };
  { T::VPROTD };
  { T::VPROTQ };
  { T::VPROTW };
  { T::VPSADBW };
  { T::VPSBBD };
  { T::VPSBBRD };
  { T::VPSCATTERDD };
  { T::VPSCATTERDQ };
  { T::VPSCATTERQD };
  { T::VPSCATTERQQ };
  { T::VPSHAB };
  { T::VPSHAD };
  { T::VPSHAQ };
  { T::VPSHAW };
  { T::VPSHLB };
  { T::VPSHLD };
  { T::VPSHLDD };
  { T::VPSHLDQ };
  { T::VPSHLDVD };
  { T::VPSHLDVQ };
  { T::VPSHLDVW };
  { T::VPSHLDW };
  { T::VPSHLQ };
  { T::VPSHLW };
  { T::VPSHRDD };
  { T::VPSHRDQ };
  { T::VPSHRDVD };
  { T::VPSHRDVQ };
  { T::VPSHRDVW };
  { T::VPSHRDW };
  { T::VPSHUFB };
  { T::VPSHUFBITQMB };
  { T::VPSHUFD };
  { T::VPSHUFHW };
  { T::VPSHUFLW };
  { T::VPSIGNB };
  { T::VPSIGND };
  { T::VPSIGNW };
  { T::VPSLLD };
  { T::VPSLLDQ };
  { T::VPSLLQ };
  { T::VPSLLVD };
  { T::VPSLLVQ };
  { T::VPSLLVW };
  { T::VPSLLW };
  { T::VPSRAD };
  { T::VPSRAQ };
  { T::VPSRAVD };
  { T::VPSRAVQ };
  { T::VPSRAVW };
  { T::VPSRAW };
  { T::VPSRLD };
  { T::VPSRLDQ };
  { T::VPSRLQ };
  { T::VPSRLVD };
  { T::VPSRLVQ };
  { T::VPSRLVW };
  { T::VPSRLW };
  { T::VPSUBB };
  { T::VPSUBD };
  { T::VPSUBQ };
  { T::VPSUBRD };
  { T::VPSUBRSETBD };
  { T::VPSUBSB };
  { T::VPSUBSETBD };
  { T::VPSUBSW };
  { T::VPSUBUSB };
  { T::VPSUBUSW };
  { T::VPSUBW };
  { T::VPTERNLOGD };
  { T::VPTERNLOGQ };
  { T::VPTEST };
  { T::VPTESTMB };
  { T::VPTESTMD };
  { T::VPTESTMQ };
  { T::VPTESTMW };
  { T::VPTESTNMB };
  { T::VPTESTNMD };
  { T::VPTESTNMQ };
  { T::VPTESTNMW };
  { T::VPUNPCKHBW };
  { T::VPUNPCKHDQ };
  { T::VPUNPCKHQDQ };
  { T::VPUNPCKHWD };
  { T::VPUNPCKLBW };
  { T::VPUNPCKLDQ };
  { T::VPUNPCKLQDQ };
  { T::VPUNPCKLWD };
  { T::VPXOR };
  { T::VPXORD };
  { T::VPXORQ };
  { T::VRANGEPD };
  { T::VRANGEPS };
  { T::VRANGESD };
  { T::VRANGESS };
  { T::VRCP14PD };
  { T::VRCP14PS };
  { T::VRCP14SD };
  { T::VRCP14SS };
  { T::VRCP23PS };
  { T::VRCP28PD };
  { T::VRCP28PS };
  { T::VRCP28SD };
  { T::VRCP28SS };
  { T::VRCPPH };
  { T::VRCPPS };
  { T::VRCPSH };
  { T::VRCPSS };
  { T::VREDUCEPD };
  { T::VREDUCEPH };
  { T::VREDUCEPS };
  { T::VREDUCESD };
  { T::VREDUCESH };
  { T::VREDUCESS };
  { T::VRNDFXPNTPD };
  { T::VRNDFXPNTPS };
  { T::VRNDSCALEPD };
  { T::VRNDSCALEPH };
  { T::VRNDSCALEPS };
  { T::VRNDSCALESD };
  { T::VRNDSCALESH };
  { T::VRNDSCALESS };
  { T::VROUNDPD };
  { T::VROUNDPS };
  { T::VROUNDSD };
  { T::VROUNDSS };
  { T::VRSQRT14PD };
  { T::VRSQRT14PS };
  { T::VRSQRT14SD };
  { T::VRSQRT14SS };
  { T::VRSQRT23PS };
  { T::VRSQRT28PD };
  { T::VRSQRT28PS };
  { T::VRSQRT28SD };
  { T::VRSQRT28SS };
  { T::VRSQRTPH };
  { T::VRSQRTPS };
  { T::VRSQRTSH };
  { T::VRSQRTSS };
  { T::VSCALEFPD };
  { T::VSCALEFPH };
  { T::VSCALEFPS };
  { T::VSCALEFSD };
  { T::VSCALEFSH };
  { T::VSCALEFSS };
  { T::VSCALEPS };
  { T::VSCATTERDPD };
  { T::VSCATTERDPS };
  { T::VSCATTERPF0DPD };
  { T::VSCATTERPF0DPS };
  { T::VSCATTERPF0HINTDPD };
  { T::VSCATTERPF0HINTDPS };
  { T::VSCATTERPF0QPD };
  { T::VSCATTERPF0QPS };
  { T::VSCATTERPF1DPD };
  { T::VSCATTERPF1DPS };
  { T::VSCATTERPF1QPD };
  { T::VSCATTERPF1QPS };
  { T::VSCATTERQPD };
  { T::VSCATTERQPS };
  { T::VSHA512MSG1 };
  { T::VSHA512MSG2 };
  { T::VSHA512RNDS2 };
  { T::VSHUFF32X4 };
  { T::VSHUFF64X2 };
  { T::VSHUFI32X4 };
  { T::VSHUFI64X2 };
  { T::VSHUFPD };
  { T::VSHUFPS };
  { T::VSM3MSG1 };
  { T::VSM3MSG2 };
  { T::VSM3RNDS2 };
  { T::VSM4KEY4 };
  { T::VSM4RNDS4 };
  { T::VSQRTPD };
  { T::VSQRTPH };
  { T::VSQRTPS };
  { T::VSQRTSD };
  { T::VSQRTSH };
  { T::VSQRTSS };
  { T::VSTMXCSR };
  { T::VSUBPD };
  { T::VSUBPH };
  { T::VSUBPS };
  { T::VSUBRPD };
  { T::VSUBRPS };
  { T::VSUBSD };
  { T::VSUBSH };
  { T::VSUBSS };
  { T::VTESTPD };
  { T::VTESTPS };
  { T::VUCOMISD };
  { T::VUCOMISH };
  { T::VUCOMISS };
  { T::VUNPCKHPD };
  { T::VUNPCKHPS };
  { T::VUNPCKLPD };
  { T::VUNPCKLPS };
  { T::VXORPD };
  { T::VXORPS };
  { T::VZEROALL };
  { T::VZEROUPPER };
  { T::WBINVD };
  { T::WRFSBASE };
  { T::WRGSBASE };
  { T::WRMSR };
  { T::WRMSRLIST };
  { T::WRMSRNS };
  { T::WRPKRU };
  { T::WRSSD };
  { T::WRSSQ };
  { T::WRUSSD };
  { T::WRUSSQ };
  { T::XABORT };
  { T::XADD };
  { T::XBEGIN };
  { T::XCHG };
  { T::XCRYPT_CBC };
  { T::XCRYPT_CFB };
  { T::XCRYPT_CTR };
  { T::XCRYPT_ECB };
  { T::XCRYPT_OFB };
  { T::XEND };
  { T::XGETBV };
  { T::XLAT };
  { T::XOR };
  { T::XORPD };
  { T::XORPS };
  { T::XRESLDTRK };
  { T::XRSTOR };
  { T::XRSTOR64 };
  { T::XRSTORS };
  { T::XRSTORS64 };
  { T::XSAVE };
  { T::XSAVE64 };
  { T::XSAVEC };
  { T::XSAVEC64 };
  { T::XSAVEOPT };
  { T::XSAVEOPT64 };
  { T::XSAVES };
  { T::XSAVES64 };
  { T::XSETBV };
  { T::XSHA1 };
  { T::XSHA256 };
  { T::XSTORE };
  { T::XSUSLDTRK };
  { T::XTEST };
};

// using Mnemonic = MnemonicInternal;

#endif // COMMON_MNEMONICS_H