name: run Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Create a container and run the binary
      run: |
        # Create a container
        docker create --name extract-container my-image-name:latest
        
        docker cp extract-container:/root/Mergen/build/lifter ./output/lifter

        # we install llvm into docker
        docker run --rm -v ${{ github.workspace }}:/data mergen

        # Remove the container
        docker rm extract-container
