name: run Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Create a container and run the binary
      run: |
        # Build the image
        docker build . --file Dockerfile --tag my-image-name:latest

        # Run the container with volume mount
        docker run --rm -v ${{ github.workspace }}:/root/Mergen/build/lifter my-image-name:latest

        docker container prune -f